### ISSUE TITLE
Planning Overview

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#1]
Plots2 issue :  https://github.com/publiclab/plots2/issues/2486 

### Layers to include

* [x] SkyTruth Alerts (https://github.com/publiclab/plots2/2451)
* [x] the Toxic Release Inventory: https://publiclab.org/q/15653
* [ ] WaterReporter.org (uses GeoJSON - http://leafletjs.com/examples/geojson/ , API : http://docs.waterreporter.org/?Javascript#your-first-request)
* [x] MapKnitter maps (https://github.com/publiclab/mapknitter/issues/251)
* [x] odor reports via https://odorlog.ushahidi.io/ via [Ushahidi API](https://wiki.ushahidi.com/display/WIKI/Ushahidi+Public+API)
API : https://odorlog.api.ushahidi.io/api/v3/posts/
* [x] http://fractracker.org/
* [x] http://www.justicemap.org/
* [ ] watershed mapper -- for which way water flows? https://www.epa.gov/waterdata/waters-geoviewer
* [x] some wind direction API for correlating which way polluted air blows at a given time and place
    * https://www.wunderground.com/weather/api/d/docs
    * others?
    * https://openweathermap.org/api
* [ ] public comments map via Scott Eustis (i'll add more detail later)

*******

- [x]  PurpleAir Layer : https://www.purpleair.com/map

- [x] OpeninfraMap Layer

### Layer submission

We should create a clear process for:

1. requesting a new layer
2. collecting links and docs, and 
3. adding it to the library in a consistent way

### UI/Navigation

I have implemented a search-bar feature on https://publiclab.org/people/ . Note that the search-bar 🔍 searches the people on map and not a particular location/place on map !
(https://github.com/publiclab/plots2/issues/2582)

* [ ] examples for how to enable/disable layers from javascript (i.e. from a separate button or checkbox for example)
* [ ] ability to open the map at a given location and zoom level using URL hashes: https://github.com/mlevans/leaflet-hash
* [ ] search for a location to re-center upon with a :mag: button and autocomplete geocoder (like at https://github.com/publiclab/leaflet-blurred-location)

### Testing : 
🔜 

### Release : 
🔜 

 - @jywarren , @mridulnagpal  feel free to edit this 😄 🎈 🗺  !

**Comment by jywarren** [comment]
Added a couple more layers and then links to APIs and libraries. Great!

**Comment by jywarren** [comment]
What do you think?

**Comment by jywarren** [comment]
This is looking awesome btw!

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ! 
Kindly have a look at https://publiclab.github.io/leaflet-environmental-layers/example/mapSimple.html .
Completed JusticeMap layer :)
<img width="718" alt="screen shot 2018-05-25 at 2 10 30 am" src="https://user-images.githubusercontent.com/14952645/40512824-9998a360-5fc1-11e8-945e-b2c59024cffe.png">

**Comment by jywarren** [comment]
Amazing!!! !!!!! So great. I love this.

Just a thought about the SkyTruth alerts -- i think they may be getting truncated? See how they seem to be on a grid - are we losing precision?

![leaflet](https://user-images.githubusercontent.com/24359/40516384-74de164c-5f7e-11e8-9826-6258a0294bed.gif)


Also can we make the demo full window size?

**Comment by jywarren** [comment]
We may need to think about a more sophisticated UI for turning on/off layers and having explanations for what they are! Let's do this much later though :-)

**Comment by sagarpreet-chadha** [comment]
The markers are getting removed due to : 
https://github.com/publiclab/leaflet-environmental-layers/blob/c4e112f6ae0a2adf2414d6678e61914d29c89106/src/skyTruthLayer.js#L87

I guess i should turn this listener off .
Will make the changes ASAP 👍 !  
Thanks 😄 !

**Comment by sagarpreet-chadha** [comment]
Oh i missed your point earlier ... Yes the markers seems to appear on a grid  .
Will look at it . Thanks !

**Comment by sagarpreet-chadha** [comment]
Great catch @jywarren 🎉  !!! Yes i was using **parseInt()** to truncate the precision . 
Done the changes 🔨  , kindly have a look !

**Comment by jywarren** [comment]
works perfectly. Great work and I'm seeing wind data too! :-)))

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren !
There are 2 PR's for mapknitter and toxicRelease Inventory . Currently working on fastTracker Layer (figuring out the API as of now) . What should we do next ?

**Comment by jywarren** [comment]
We got an inquiry about PurpleAir air quality sensors. I think Wunderground
has a data layer for air quality -- they may also have higher resolution
wind data. So maybe,

* PurpleAir sensor data?
* Wunderground weather/wind direction data?

Also, we can skim through the Public Lab site for posts about map
databases. Marlokeno may have great ideas:

https://publiclab.org/questions/marlokeno/09-02-2017/how-can-the-public-find-or-make-maps-of-the-polluters-next-door

* that page mentions EJ Screen: https://www.epa.gov/ejscreen
* Energy Justice Map - we may need to reach out to contact them for an API
link? http://www.energyjustice.net/map/

More here too!

https://publiclab.org/questions/warren/02-01-2018/is-there-a-way-to-view-epa-s-toxics-release-inventory-on-a-map-or-by-location

Leave some comments maybe?

**Comment by sagarpreet-chadha** [comment]
mapknitter layer and ToxicRelease Layer pushed to gh-pages branch .

**Comment by sagarpreet-chadha** [comment]
@jywarren 
Wunderground API shows same data as OpenWeatherMap API .
What do you think ?

This is the current OpenWeatherMap Layer we have : 
Solved in this commit : f38d59419c4e88af855ec2172c1b5b44192a8be3
(Did not made a separate PR for this Layer ! ) 

<img width="1162" alt="screen shot 2018-06-26 at 4 28 45 pm" src="https://user-images.githubusercontent.com/14952645/41907381-4d59cb6c-795e-11e8-8b92-0f8bde2bbac6.png">

**Comment by jywarren** [comment]
OK, sounds good. I was just wondering if there's any higher resolution wind
data out there, but that sounds fine!

**Comment by sagarpreet-chadha** [comment]
@jywarren ...to get data from **epa** site , we have to contact them .

ALSO we can show Power , Telecom , Petroleum , Water layers from https://openinframap.org/#4/46.68/-87.98/Water 

What do you think ?

**Comment by jywarren** [comment]
Hi, which EPA site and which API? The EPA is not a good agency right now,
with the current leadership, so we will not likely get cooperation. But
there are other organizations "mirroring" EPA data that we may be able to
rely on.

**Comment by jywarren** [comment]
Openinframap sounds interesting! Where does their data come from?

**Comment by sagarpreet-chadha** [comment]
Its part of https://www.openstreetmap.org .....hence data is crowdsourced . 

_By and large, this data isn't exposed on the main OSM map, so I built Open Infrastructure Map to visualise it._
Source : https://openinframap.org/about.html

**Comment by jywarren** [comment]
Wow, ok! Let's do it!

**Comment by jywarren** [comment]
Great find and great idea! Maybe we should ping @numeroteca on
PublicLab.org for more data like this because he's into tracking
landfills...

**Comment by sagarpreet-chadha** [comment]
I was reading about EPA and it makes sense that we will not get any help from them .
I have searched for sites that mirror the data but couldn't find any that we can use . 

Thanks !  Asking on Publiclab.org .

**Comment by jywarren** [comment]
Hi, @sagarpreet-chadha there seems to be some code samples here for the first EPA dataset: https://www.epa.gov/waterdata/navigation-delineation-service for watersheds... take a look?

**Comment by jywarren** [comment]
Ah, i'll share over here: https://publiclab.org/questions/sagarpreet/07-01-2018/what-more-data-layers-can-we-show-on-map

**Comment by sagarpreet-chadha** [comment]
Okay great ! Looking at the code samples 👍 .

**Comment by jywarren** [comment]
Closing in favor of #134
