### ISSUE TITLE
Using Mapknitter API

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#10]
Hi @jywarren !

The construction of API for fetching data is solved here : https://github.com/publiclab/mapknitter/issues/251

The corresponding API example is : https://mapknitter.org/map/region/Gulf-Coast.json?minlon=-98.8&minlat=23.6&maxlon=-79.1&maxlat=31.8

We can get the map centers from leaflet library using : 
`var center = _map.getCenter() ;`
and Latitude is then `center.lat` and longitude is `center.lng` .

**Using this how should we set the minlon , minlat , maxlon , maxlat parameters in the API url ?**

Thanks :octocat: !

**Comment by jywarren** [comment]
I think Leaflet has a bounding box request?

**Comment by sagarpreet-chadha** [comment]
So we need NorthEast coordinates and SouthWest coordinated of the Bounding box , right ?
See here : https://leafletjs.com/reference-1.3.0.html#latlngbounds-getnortheast

So ,
NorthEast coordinate = maxlat and maxlon
SouthWest coordinate = minlat and minlon 
is this correct @jywarren ?

**Comment by jywarren** [comment]
i think so - give that a try! We can also swap around a bit if it doesn't
work in all scenarios.

**Comment by sagarpreet-chadha** [comment]
PR #13 .
