### ISSUE TITLE
Abstract Google Spreadsheet Class

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/leaflet-environmental-layers#102]
Referring to [this](https://github.com/publiclab/leaflet-environmental-layers/pull/97#issuecomment-445287742).

I feel we could create a new class that extends LayerGroup called SpreadsheetLayer. 

In its options, it could take the desired url. I feel like the URL needs to be the one that gives the JSON output, though there might be a way to make several requests and find that url (see [here](https://sandbox.idre.ucla.edu/sandbox/general/databasing-google-spreadsheets-to-json), just like the one I used in #97 ). 

I feel it should also take the desired column headers, or if there are no headers, then column numbers, including specifications for the latitude and latitude columns.

So we can create a generic parseData, requestData, clearOutsideBounds that works for all of these sheets.

Then the user needs to supply a generatePopup method to specify the text. This could be a method or even a template literal.

I will see what I can do as I go :smile: .

**Comment by kevinzluo** [comment]
Could this be assigned to me?

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/4746645406220288/
@kevinzluo

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/4746645406220288/
@kevinzluo

**Comment by jywarren** [comment]
Perfect!
