### ISSUE TITLE
Bounding box ordering, re-centering issues?

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#110]
I opened the Wisconsin Non-Metal layer but then it tries to recenter on a very broad bounding box:

![image](https://user-images.githubusercontent.com/24359/50857386-7a850380-135b-11e9-910d-9898d75e5cb3.png)

https://publiclab.org/people#12/43.9929/-90.3883/BL1-Wisconsin_NM

Wondering if there is some better ordering we need to do to manage how the re-zooming leaves things once all layers are loaded. Ideas?

**Comment by sagarpreet-chadha** [comment]
Okay , so what is happening is that **LEL** first re-centers to the correct bounding box according to the URL , but after few milliseconds **plots2** re-centers to my personalized view bounding box according to my location OR if you have not shared location , the default is to set to zoom level 2 .

**Comment by sagarpreet-chadha** [comment]
* We definitely should remove the default zooming to level 2 . 
* When we choose WisconsinLayer we are forcefully zoomed and panned . Lets remove this also !

After this , if you have not shared your location - then everything will work fine 👍  . 

But if you have shared your location - it will show your location centeric bounding box AND not the correct one according to the URL . So to solve this , i was thinking showing a link below the map - **_"Show nearby things or something"_** , on clicking it show nearby view .

What do you think ?

**Comment by jywarren** [comment]
I think perhaps the issue is that some layers only make sense in some
regions. Could we turn off all auto-zooming, but have some layers that are
regionally specific only appear if your bbox overlaps the relevant region?
I know that would be a big project, but it seems logical, no?

**Comment by jywarren** [comment]
OK @sagarpreet-chadha can we start with stopping the layers from recentering, as a first step? Thank you!

Also, I can't seem to get links at zoom level 12 (or any higher than 7) to work when loading a new map. For example: https://publiclab.github.io/leaflet-environmental-layers/example/#12/44.3913/-91.0156/BL2-Wisconsin_NM-FT_mobile-Purple-STruth-windrose-AQI 

This should open at zoom 12, but it opens at zoom 7. I think this is the same issue, maybe? I'd like to see this as the default view:

![screen shot 2019-01-15 at 2 34 44 pm](https://user-images.githubusercontent.com/24359/51205087-16ba8780-18d3-11e9-86c7-e509bb2e65be.png)

**Comment by sagarpreet-chadha** [comment]
On it 👍 ! Yes happening due to same reason of implicit zooming of some layers causing url to work improperly .

**Comment by avsingh999** [comment]
@jywarren @sagarpreet-chadha we have to change all layers default zoom level 12. Am I right
thanks

**Comment by jywarren** [comment]
Hi @ananyaarun @sagarpreet-chadha  -- this will be an interesting one to try to work into the idea of standardized layers. In your new plan, does each layer have a kind of "info" properties, sort of like how each module in Image Sequencer does? 

https://github.com/publiclab/image-sequencer/blob/2c58edfe9a8f201675d0d601e9771dbfa104c493/src/modules/Blur/info.json#L1-L15

One advantage here is that we can turn of auto-zooming (this may already be done?) but then we can make layers visible/hidden according to how they define their range of zooms and the extend of their data. 

```
{
  name: 'Wisconsin Non-Metallic Mining',
  url: 'https://example.com/docs',
  extents: {
    minLat: 0,
    maxLat: 0,
    minLng: 0,
    maxLng: 0,
    minZoom: 2,
    maxZoom: 6
  }
}
```

Sorry if i'm not synced up with your latest planning but wanted to highlight how such a structure could help solve problems like these!

**Comment by jywarren** [comment]
Link to #1 #198

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ,

* I have checked the Leaflet URL hash, and we can share links with zoom level upto 18 . 
https://publiclab.org/people#16/21.1257/57.1309/BL1

So following questions : 

1. Remove all autozooming and autopanning from LEL?

2. In plots2, there is autozooming and autopanning based on your location, which we cannot use with Leaflet Hash . 
- What happens now is that the URL pans and zooms somewhere BUT after 3 seconds if location is shared then map zooms/pans to users locations . What to do here?

Thanks!
