### ISSUE TITLE
Add Code of Conduct to this repository

### ISSUE THREAD

**Issue by gauravano** [publiclab/leaflet-environmental-layers#114]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/leaflet-environmental-layers/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Create** the file named [CODE_OF_CONDUCT.md] in the `leaflet-environment-layers` repository (press the little pen Icon) and edit the line as shown below. 

[See this page](https://publiclab.github.io/community-toolbox/#r=all) for some help in taking your first steps!

The file needs to be created at the root of the repository and copy the code of conduct from https://github.com/publiclab/plots2/blob/master/CODE_OF_CONDUCT.md

into newly created file. 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by sagarpreet-chadha** [comment]
Awesome 👍 💃 😄 !

**Comment by harsh1599** [comment]
May I do this?.. As it's been a long time since this issue was opened..

**Comment by nkleinbaer** [comment]
I would like to claim this issue. I created the document and modified the information at the top about when and where it was copied from. [Pull request here ](https://github.com/publiclab/leaflet-environmental-layers/pull/115)

**Comment by jywarren** [comment]
Hi I'm sorry we didn't respond! We'd love help and will review the PR. I'm
sorry Harsh, could we get you plugged into another issue maybe?

**Comment by nkleinbaer** [comment]
> Hi I'm sorry we didn't respond! We'd love help and will review the PR. I'm sorry Harsh, could we get you plugged into another issue maybe?

Who is Harsh? Was someone already working on this issue? I see that lot's of other public lab projects have identical issues - should I work on one of those, instead?

**Comment by jywarren** [comment]
Sorry, i replied by email and my inbox showed someone else expressing
interest. It looks like the comment had been deleted however. Sorry for the
confusion, we're happy to receive your PR! Thanks a lot!

**Comment by gauravano** [comment]
Hi @nkleinbaer, actually @jywarren replied via Email thread so there might be a contributor before you by name Harsh who may have asked for claiming this issue but deleted his comment from GitHub later, so that's why @jywarren mentioned him.
