### ISSUE TITLE
Move some dist/___ files into src/____

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#120]
After #104, we now have some additional files in /dist/ --

https://github.com/publiclab/leaflet-environmental-layers/blob/master/dist/legendCreation.js

There's also:

https://github.com/publiclab/leaflet-environmental-layers/blob/master/dist/windRoseLayer.js

These ought to be re-integrated back into the main library in `/src/____`, to be compiled into the main project. We'd love help doing this!

We should then be able to tidy up the Readme and the `example/index.html` files!

**Comment by avsingh999** [comment]
@jywarren  I want to work.
thanks : )

**Comment by jywarren** [comment]
yes please!

**Comment by sweezy793** [comment]
Can I work on this issue?

**Comment by avsingh999** [comment]
@sweezy793  I am working on it. I am late because I am getting some error while ```npm install ``` but I will send pr as soon as possible
Thank you : )

**Comment by gauravano** [comment]
Hey @sweezy793, you can look at other issues of Leaflet - https://github.com/publiclab/leaflet-environmental-layers/issues or can grab a first-timer-issue from https://code.publiclab.org/#r=all. Feel free to leave a comment if you are not able to find an issue to start, we are here for help. Thanks!

**Comment by gauravano** [comment]
Hey @avsingh999, feel free to open the PR irrespective of error as others can also help you in error resolution, if you open the PR. Thanks!

**Comment by avsingh999** [comment]
@jywarren @gauravano @sagarpreet-chadha please close this isuue.
thanks : )
