### ISSUE TITLE
Adding info about Mapknitter Layer in the article.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/leaflet-environmental-layers#129]
The Mapknitter layer's details has a line `For more info on MapKnitter Layer, visit here`, in which `here` directs to `https://publiclab.org/notes/sagarpreet/06-06-2018/leaflet-environmental-layer-library?_=1528283515` . But, there is no information about Mapknitter Layer in the blog. 

Example - https://publiclab.github.io/leaflet-environmental-layers/example/#3/43.00/-53.12/BL2-MapK

**Comment by sidntrivedi012** [comment]
@jywarren @sagarpreet-chadha Please take a look. May I add the details of the layer in the blog or should I direct it to some other link?

**Comment by jywarren** [comment]
Perhaps we should just link to MapKnitter.org? Thank you!

**Comment by sidntrivedi012** [comment]
@jywarren @gauravano Is anyone working on it? If not, I can fix it. Just requires changing of a link

**Comment by gauravano** [comment]
Go ahead @sidntrivedi012. Thanks!

**Comment by sidntrivedi012** [comment]
Closing it since it has been solved in #155.
