### ISSUE TITLE
Display "new items" mark in Layers menu when you enter an area with a new layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#133]
Some layers are really concentrated on only one region, and we have a proposal to display those layers only when you're with in the bounding box for that layer. 

This will take some work -- #117 -- but once it's complete, we could actually alert users that there is new information to display by showing either a red dot or a small number (like the "new emails" dot on some phones) which calls your attention to the new layers:

![image](https://user-images.githubusercontent.com/24359/53990115-8a1f8f00-40f5-11e9-9686-f200b1ebcd01.png)

There are multiple places we could highlight the new layers, but we might show them in a group at the top of the layers menu here:

![image](https://user-images.githubusercontent.com/24359/53990102-84c24480-40f5-11e9-8ae4-c302bd894fd9.png)

We might also show them in #59's larger layer browser. 

This can't be worked on until #117 but saving it for later!

**Comment by stefanosu** [comment]
Hello @jywarren and @gauravano is there any help that is still needed on this issue I would love to contribute thanks.

**Comment by sagarpreet-chadha** [comment]
Hey Stefanos, yes you may work on this.

**Comment by stefanosu** [comment]
@sagarpreet-chadha  Hey I'm having the trouble of where to I should make a PR for this.

**Comment by crisner** [comment]
@sagarpreet-chadha, @jywarren, How shall we implement this with what we have now? 
Do we go with something like this or shall we add in the text to make it look like the mock above?
![notification](https://user-images.githubusercontent.com/29401459/71641875-8e421c00-2cc8-11ea-8fb3-8acd06922fb8.png)

**Comment by sagarpreet-chadha** [comment]
I think all layername should be visible in the layername at all times. 
When the data is fetched for a layer which is only visible at a small area (when we move map to that area), then the red dot should be there i guess.

Earlier we could have not shown the layers in the menu  if they are visible only at very small area, but i think the new menu bar cleanly shows all the layers.

Lets wait for @jywarren on this one before starting work! Thanks :)

**Comment by crisner** [comment]
Yes. Let's. Thanks! 😄

**Comment by jywarren** [comment]
Wow all are beautiful! After thinking about it a while I think the 3rd
(southwest) mockup is the clearest! Let's add text in a popover, perhaps?
Instead of in the button?

**Comment by jywarren** [comment]
Sorry I meant a tooltip, not a popover!

**Comment by crisner** [comment]
Great, thanks! I'll implement it as shown in the 3rd type in the mockup with text in a tooltip.
