### ISSUE TITLE
Guide to how to add new layers

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#136]
Along with a layer submission system like #135 for people who find layers we'd like to add, we should have a README documentation section on how to actually add new layers in code. This could point at a PR which demonstrates everything you need to add one, for new coders to help out!

It could be like this file, although probably a lot simpler: 

https://github.com/publiclab/image-sequencer/blob/main/CONTRIBUTING.md#contributing-modules

**Comment by ephemeralwaves** [comment]
I'd like to help work on this because I would like to work on  #119  and I'm trying to figure out how exactly to go about adding a layer myself. Would anyone be able to help me through this process? So far I've gotten the data from #119 and found an npm module to get/add the lat/lng data into the csv file.

**Comment by sidntrivedi012** [comment]
Thanks a lot @jywarren for this. Have been working on #116 but facing some issues. This will really ease the things a lot. :tada:

**Comment by jywarren** [comment]
We may need some input from @sagarpreet-chadha on this, but basically, we add a new layer in the folder with the other layers, and for many layer types we can copy an existing one and modify it. 

We should make a list of what's needed, and perhaps link to a PR or two of when other layers were added, as an example. But this may need to be an evolving guide, as we're also looking to make it easier to add new layers!

Here are a couple example PRs:

* https://github.com/publiclab/leaflet-environmental-layers/pull/94
* https://github.com/publiclab/leaflet-environmental-layers/pull/92
* https://github.com/publiclab/leaflet-environmental-layers/pull/78

However, some of those layers were moved into their own code files in this PR, which is the preferred way to store them: https://github.com/publiclab/leaflet-environmental-layers/pull/108

I hope this is at least a little helpful, but I think it's also a chicken and egg 🐔 🥚  problem because having a guide would help us keep this library more structured in the first place! Thank you for your interest and help!!! We're open to ideas here too! 👍 🎉

**Comment by rkpattnaik780** [comment]
Hello, I have recently worked on adding layers and I think I can describe the procedure of adding a layer that will be beginner friendly. I feel that providing examples in codepen and a descriptive tutorial along with sample PRs might also be helpful for a beginner. What do you feel @jywarren ?

**Comment by jywarren** [comment]
That would be really awesome. Perhaps open a PR with a draft? You could add
it to the README, or make a new markdown file called CONTRIBUTING.md.
Thanks!

**Comment by rkpattnaik780** [comment]
@jywarren I think a new file CONTRIBUTING.md will be better. I will make the PR as soon as possible. :)

**Comment by jywarren** [comment]
awesome!!

**Comment by rkpattnaik780** [comment]
@jywarren I have made a [codepen sample](https://codepen.io/rkpattnaik780/full/MxMRBP) where luftdaten layer has been implemented. Does it seem sufficient to be included as a sample for guide to add new layers ?

**Comment by jywarren** [comment]
sure, anything will probably help! Thank you!

**Comment by jywarren** [comment]
Hi @crisner, just putting this on your radar. With all the fantastic work that's gone into this library, perhaps we should revisit the "adding a layer" docs in CONTRIBUTING.md - maybe adding the "spreadsheet layers" too, like #154?

**Comment by jywarren** [comment]
Ah, actually we have some suggested text for spreadsheet layers here! https://github.com/publiclab/leaflet-environmental-layers/issues/121

**Comment by crisner** [comment]
I guess this issue #243 is related?
