### ISSUE TITLE
OSM Landfills, Mines and Quarries checkbox not working.

### ISSUE THREAD

**Issue by sidntrivedi012** [publiclab/leaflet-environmental-layers#139]
@jywarren @sagarpreet-chadha The checkbox of the last layer is not ticking and thus, the layer is not being visualized.

**Comment by sidntrivedi012** [comment]
![LEL1](https://user-images.githubusercontent.com/31186013/54106671-e851b800-43fc-11e9-985c-26b2e06c4b06.gif)

**Comment by sidntrivedi012** [comment]
It is disabled in the HTML.
![Screenshot from 2019-03-11 13-22-07](https://user-images.githubusercontent.com/31186013/54108021-de31b880-4400-11e9-84f0-2e9200f4b9df.png)

**Comment by gauravano** [comment]
@sidntrivedi012 would you like to fix this yourself?

**Comment by sidntrivedi012** [comment]
@gauravano Sure. I would love to.

**Comment by gauravano** [comment]
Great!

**Comment by rkpattnaik780** [comment]
@sidntrivedi012 the minimum zoom for OSMLandfillMineQuarryLayer has been deliberately set to 7, which enables the checkbox only when zoomLevel >= 7. We might remove the minimum zoom if it does not break anything else :).

**Comment by jywarren** [comment]
I think we were potentially worried about making too large a query to the
server -- like, requesting all data for a huge swath of the planet. So,
perhaps we need to look closer and just be careful about exceeding API
limits?

**Comment by anu-shree** [comment]
I want to work on this issue!
We can fix this issue by displaying an alert for zoom level < 7 and of keeping the checkbox disabled.

**Comment by sidntrivedi012** [comment]
Hey @anu-shree , though it has been assigned but still you are welcome to work on this issue. If you find the solution, do make the PR.

**Comment by anu-shree** [comment]
Thanks! I will soon send a PR!

**Comment by sidntrivedi012** [comment]
@anu-shree Are you working on it ?

**Comment by ananyaarun** [comment]
Hey, so over here I tried to reproduce this issue. On removing minZoom =7 , as @jywarren said data takes way too much time to load. On the otherhand , with min zoom levels defined it works well.

- we can either compromise on time and remove the minZoom =7 
- or add a zoom in in bracket like the pressure contour layer

What do you think @jywarren @sagarpreet-chadha ?
