### ISSUE TITLE
Declare character encoding for the HTML document.

### ISSUE THREAD

**Issue by rkpattnaik780** [publiclab/leaflet-environmental-layers#145]
Opening the `example/index.html` page in firefox gives the following warning in console.

![image](https://user-images.githubusercontent.com/23582438/54366359-86ac7a80-4696-11e9-8fac-ff7c9957a883.png)

This might require addition of just a meta charset attribute within `head`.

**Comment by rkpattnaik780** [comment]
We can make this a `first-timers-only`. Just a really minor change that's considered a good practice :).

**Comment by jywarren** [comment]
Awesome!

**Comment by ananyaarun** [comment]
Hey, I'll take this up as my first contribution to this repository. :)

**Comment by gauravano** [comment]
@ananyaarun please mention this issue in your PR. Thanks!
