### ISSUE TITLE
Fix low hanging jshint errors

### ISSUE THREAD

**Issue by mmmelissa** [publiclab/leaflet-environmental-layers#150]
As a developer, its hard to ulilize jshint if there are many previous unfixed/un-ignored errors. In order to reduce noise and increase developer use of jshint, we should fix as many errors as possible.

**Comment by mmmelissa** [comment]
@jywarren, I am trying to push a new branch  for this, and it looks like I dont have permission. Could I be added to this project? Thanks!

**Comment by jywarren** [comment]
Hi! For sure although I'm on my phone right now not my laptop, so I will ASAP... The other thing you can do is push to your own GitHub remote branch and then open a pull request from there. I believe git will prompt you to open a pull request once you push, or you can go to the front page of this repository after pushing and I believe a prompt will appear then. 

Thank you very much! 🎉

**Comment by mmmelissa** [comment]
Hey @jywarren,did you forget about me?:(  Could I be granted push access so I can push these changes? Thanks.

**Comment by gauravano** [comment]
I guess @jywarren is busy. He hasn't appeared today on any issue. You can open PR for this one. Thanks!

**Comment by jywarren** [comment]
So sorry! Yes, i'm trying to catch up but very very behind! You should be able to push to your own remote branch at https://github.com/mmmelissa/leaflet-environmental-layers (or `git@github.com:mmmelissa/leaflet-environmental-layers`) without needing push access, and then you can open a pull request -- for more on this, see the article on "Github Flow" here: http://publiclab.org/developers#Resources

I hope that helps, and apologies again for being slow!
