### ISSUE TITLE
Add industrial sites (in RI) database

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#157]
![image](https://user-images.githubusercontent.com/24359/61895038-aaeb5400-aedf-11e9-883a-4a300d5a2242.png)

https://datasci.brown.edu/socio-eco-project/

This may take some work, as it includes a timeline slider! But it uses MapBox.js (built on Leaflet), possibly to achieve it. Needs some research!

**Comment by jywarren** [comment]
Hi @ananyaarun @sagarpreet-chadha -- would it be possible to add this using the standard layers system? And, how easy is it to extend a standard layer with additional features like, say, a timeline range slider?

**Comment by ananyaarun** [comment]
If this layer can use the same standard file then only a few conditions like the url, request data , add marker methods need to be added. This will be as an extension to the existing if else ladder.

If a new feature like displaying a timeline range needs to be added it just has to be written as a new function in the file.

**Comment by jywarren** [comment]
That's awesome. Would you like to try taking a first pass at this?

Also, are you using a standard "popup generator" template function as part
of the new standard layers? Would there be some chance to provide easy
customization building on that, and is it documented in the README? This
will be a common way people will want to customize their layers.

Thanks Ananya, this is so exciting!

**Comment by ananyaarun** [comment]
Sure, soon after a few tests get working and are in place, I shall document the new standardized layers in readme.

**Comment by jywarren** [comment]
awesome, thank you!

**Comment by jywarren** [comment]
Looked further into this and it uses the following markup:

```html


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.48.0/mapbox-gl.js"></script>
<link href="https://datasci.brown.edu/socio-eco-project/static/css/main.cdf721c7.css" rel="stylesheet">
<div id="app"></div>
<script type="text/javascript" src="https://datasci.brown.edu/socio-eco-project/static/js/main.d29369e3.js"></script>
```

However, this file contains both the script AND the entire database of sites, in GeoJSON 😮 

https://datasci.brown.edu/socio-eco-project/static/js/main.d29369e3.js

We can probably get it out of there!

**Comment by jywarren** [comment]
I got the GeoJSON out - it is 4.2mb. 

Here's a layer to model this on: 

https://github.com/publiclab/leaflet-environmental-layers/blob/069ec411e853710714d217af7e1c63c5ead03dda/src/eonetFiresLayer.js#L15

**Comment by jywarren** [comment]
Great progress in #279!
