### ISSUE TITLE
Add PR and issue template in the .github folder

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#159]
# Description
Currently the .github folder of the repo has only a FTO issue template.
# Solution
The regular issue template and PR template can be added here like other public lab repositories.
https://github.com/publiclab/plots2/blob/master/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
https://github.com/publiclab/plots2/blob/master/.github/PULL_REQUEST_TEMPLATE.md

If approved I'd like to add these templates in their respective directories
Thanks!

**Comment by jywarren** [comment]
This sounds super! We'd love your help with this! You might look at https://github.com/publiclab/plots2/issues/3681 to get started? Thanks!
