### ISSUE TITLE
Fractracker Layer 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#16]
This map shows the location of organizations working on oil & gas issues in the US and internationally.
http://ft.maps.arcgis.com/apps/Embed/index.html?appid=8defce10bdc64a35ae4fd3997edd2b1e

The data set of this map is here : 
https://docs.google.com/spreadsheets/d/19j4AQmjWuELuzn1GIn0TFRcK42HjdHF_fsIa8jtM1yw/pub?gid=288258812&single=true&output=csv

🛢 🛢

**Comment by sagarpreet-chadha** [comment]
@jywarren ...how can we show CSV data onto our map ?

**Comment by sagarpreet-chadha** [comment]
I converted CSV to JSON and uploaded it to my github for now .
Here : https://sagarpreet-chadha.github.io/FractrackerCSV.json

**Comment by jywarren** [comment]
I think it may have to be parsed each time we fetch it, unless there's a
Leaflet CSV library?

**Comment by sagarpreet-chadha** [comment]
Solved in #17 .
