### ISSUE TITLE
Rename Baselayers to add names like greyscale,streets,satellite etc

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#161]
# Description
Currently the map has 4 baselayers named
- Baselayer1
- Baselayer2
- Baselayer3
- Baselayer4

It is not very intuitive for a general user to understand what these layers mean or display.

# Solution
The layer names can be changed to something more descriptive such as
- Standard
- Grey-scale
- Streets
- Dark

**Comment by ananyaarun** [comment]
@jywarren , @gauravano , @sagarpreet-chadha 
Any better suggestions for the names ? 
I would like to work on this issue once finalized and approved :)

**Comment by gauravano** [comment]
Nice idea @ananyaarun! Let's wait for Sagarpreet's and Jeff's approval before start here. Thanks!

**Comment by sagarpreet-chadha** [comment]
Hi @ananyaarun ,
Yes you may go ahead and solve this . Great thinking :)
