### ISSUE TITLE
Weekly Community Check-in #17 - Enhance User Experience

### ISSUE THREAD

**Issue by gautamig54** [publiclab/leaflet-environmental-layers#164]
Hi everyone 👋 !

We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️ .

If you're new here, welcome 🎈 , and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us 🔃 and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our [Gitter](https://gitter.im/publiclab/publiclab) chatroom 👐 .

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation 📟 .

### This Week's Theme
Since Public Lab is a community which addresses environmental issues and open to users all around the globe, I thought of making this week's theme as "Enhancing the user experience". 
This week, contribute to Public Lab by raising UX issues or increasing the accessibility of the website or reducing the number of queries in order to make the website faster. We can suggest new ideas which can further supplement to the User Experience. 

### Welcome new contributors!
 I would encourage new contributors to try different kinds of [FTOs](https://github.com/publiclab/plots2/issues?utf8=%E2%9C%93&q=first-timers-only) and [help-wanted issues](https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22). Since open source is all about community and helping others, let's find some issues which might be good for someone else who is contributing or just beginning and help them solve it. Let’s expand our community as much as we can! 🎉

### Google Summer of Code
There is a list of amazing ideas for GSoC, 2019. It is a result of continuous brain-storming by our mentors and contributors. 
Check out the ideas at https://publiclab.org/wiki/gsoc-ideas and join us for a riveting journey and a great learning experience. 

The proposal can be submitted at https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals to get reviews from the mentors.

Along with this, our past GSoC members Vidit, Naman, and Sagarpreet gave this GSoC Webinar, where they explained the procedure of this program and explained their previous year proposals for Public Lab. Also explained their idea page for SoC programs as well.
https://www.youtube.com/watch?v=BNhBd_WfKVA&t=618s.
This is amazing and would be helpful to all the GSoC aspirants!

cc
@mohitRJranjan @milaaraujo @kevinzluo @Rishabh570 @sashadev-sky @geekychaser @shubhscoder @sidntrivedi012 @SidharthBansal @cesswairimu @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @IshaGupta18 @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @romanrodriguez @Dhiraj240 @codeIriss @rishabhc32 @chirag-singhal @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @HarshKhandeparkar @aashna27 @Harshithpabbati @marieram @swiatek7 @kaunair @CleverFool77 
@niravasher @gautamig54

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.

People who did the check-ins-

Sidharth Bansal (@SidharthBansal)
Cess (@cesswairimu )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@IshaGupta18)
Gaurav Sachdeva (@gauravano)
Harshith Pabbati (@Harshithpabbati)
Gaurav Sachdeva
Harshith Pabbati (@Harshithpabbati)
Harman Jolly (@CoderJolly )
Divya Baid (@divyabaid16)
Gautami Gupta (@gautamig54)

Have a great week everyone 🎈 🎉 🎇

**Comment by jywarren** [comment]
Thanks for a great check-in!!!

Hey, everyone! @souravirus has just completed a really huge refactor of all
of plots2 into Bootstrap UI v4.0!

We'd love help trying it out and finding any issues -- read more here!

https://github.com/publiclab/plots2/pull/3937#issuecomment-480566033

@souravirus @gauravano is that the right place to leave any feedback?

We're going to try to merge this very soon, and we want to try to catch as
many issues before then as possible! Thanks all, and congratulations
@souravirus!!!

**Comment by gauravano** [comment]
Hey everyone!

Test the website at https://unstable.publiclab.org and if you come across any issue, report them at https://github.com/publiclab/plots2/issues/5182. If you are interested in going through the Bootstrap 4 Upgrade, then check out  https://github.com/publiclab/plots2/pull/3937

The bootstrap upgrade is done by @Souravirus. Really AWESOME work :tada: :100:

**Comment by gauravano** [comment]
@marieram @swiatek7 @kaunair @gauravano @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps

@subhahu123 @An0u @Jaya738 @mgroovyank @shreyateeza @TANGL3SIT3S @nazeem1988 @karunagoyalk @Nirvikalpa108 @cassianoblonski @EngrEric @Anjalizi @GettyOrawo @coderbeetle @corbettbw @govindjeevan @gautamig54 @daddyjab @emestabillo @letnewKid @srujana121 @jazdao @ChinwenduSilvia @aggarwal19 @Jenniline @madelinejones @helenatxu @richa031 @fabsar @kuja24 @megha070 @Aarabhi2017 @Manvi07 @siddhishree @Julius26 @VinneyJ @sonali9696 @rarrunategu1 @coreytegeler @labseven @milomacphail @CleverFool77 @ananyaarun @ananya @divyabaid16 @publiclab-mimi

**Comment by gauravano** [comment]
@shubhi2000 @Priyak5 @vaarigupta @techchic @ananya @hc-barker @edwd42 @PritiShaw @themonster2015 @supriya-kotturu @AnthoniaOkafor @jtmims @scheleon @mahmodHammad @santushk @jillpena @stoic-plus @vaarigupta @alonpeer @madeofhuman @ibnjunaid @HarshKhandeparkar @aashna27 @Harshithpabbati @niravasher @mmmelissa @madhavsarpal100, @sameersidd, @Anupam-dagar, @stephenmasih @jainaman224 @starcruizer @mahmodHammad

**Comment by alonpeer** [comment]
I haven't had any time last week for OSS. 

This week I would like to see my PRs merged ([this one](https://github.com/publiclab/plots2/pull/5338) and [that one](https://github.com/publiclab/plots2/pull/5307)), so we can finally get rid of the `node.legacy_view` column, and maybe get a bit of performance boost for page load.
I'd also be curious to know how the page load latency can be tracked. Is there some metrics tool that we're using? Something like [honeycomb.io](https://www.honeycomb.io/)?

Other than that, I'd like to hunt for another backend bug/feature to work on, probably on Wednesday. I'm open for suggestions!

**Comment by jywarren** [comment]
Hello all! A request from a cool sounding group in California: 

> Write/Speak/Code is a nonprofit that seeks to promote the visibility and leadership of technologists with marginalized genders through peer-led professional development. The San Francisco chapter's Open Source event is this April 17th and they're looking for PL mentors who identify as trans, non-binary, or woman to help attendees contribute to the PL OSS project. Mentorship can be in person or through a public Slack channel. For more information, feel free to email the event lead Mimi at tienmiminguyen@gmail.com. Here's the event link: http://meetu.ps/e/Gh49J/zXGBX/f

I'd be happy to help create some first-timers-only issues in support of this if anyone is interested in being a mentor for this event!

**Comment by ebarry** [comment]
Hi everyone, 
This week I'm looking for someone who has been part of Public Lab for a long time, for instance @cesswairimu @SidharthBansal @gauravano @jywarren or others to review a 17 page report of the Software Contributors Survey, and then join a discussion on what our high-level takeaways should be.

**Comment by jywarren** [comment]
Lots going on in communities and efforts we're connected with this week; Coraline Ada Ehmke (author of the Contributor Covenant code of conduct) asked on Twitter:

> Have you ever experienced an act of kindness from a maintainer when you contributed to an OSS project? I’d love to hear your story and incorporate it into a chapter on open source citizenship!

https://twitter.com/CoralineAda/status/1115391442778824705

We have so many kind people in this community who help each other each day. Consider replying to Coraline if you have a story to share!

**Comment by skilfullycurled** [comment]
Hi everyone,

Just introducing myself.  I'm Benjamin and I'm a long time member of Public Lab but this is my first time working on the site.  I'm going to be working on [#5412](https://github.com/publiclab/plots2/issues/5412) issue which is sort of a situation of my own making from [#5268](https://github.com/publiclab/plots2/issues/5268), with its beginnings in [#1502](https://github.com/publiclab/plots2/issues/1502).  Anyway, while I do program, I've never programmed in Ruby/Rails (although I can read it pretty well and am familiar with the MVC paradigm).  I'm really excited because it has been frustrating to have the skills and desire to contribute but lack the language/process knowledge (despite the dev group being so welcoming and making it easy to join in). 

Looking forward to working with everyone!

**Comment by alonpeer** [comment]
Great to have you onboard @skilfullycurled !
I'm pretty new to Public Lab, but have plenty of Ruby/Rails XP. Let me know if I can assist in any way 😄

**Comment by gauravano** [comment]
Hi everyone, 

This week's goals:
1. Going through mentions and old issues/PRs at plots2
2. Completing PR at Mapknitter
3. Some sorting out at LEL, PL.Editor, Community toolbox, IS and plotsbot

@ebarry count me in for the Survey reviewing and discussion. 

For all the early career Ruby devs as well as seasoned ones, there is a mentorship program https://rubyme.org/ which pairs beginners with the mentors to work on an Open Source project. Deadline for this program is April 15. Go through the above link to read full details and apply if you want to some time of your summer learning Ruby :gem:  

Have a great week all :100:

**Comment by sagarpreet-chadha** [comment]
@ebarry , i would love to take part in this discussion :+1: .

**Comment by skilfullycurled** [comment]
Hey everyone,

Can I trouble someone to respond to a comment I left at https://github.com/publiclab/plots2/issues/5412#issuecomment-481789159?  Since the text on the pull request said to do X, Y, and Z before requesting the pull, I marked it as a draft pull request.  However, now the tests aren't running, and I didn't want to mark it for review without running them.  Should I close it and make a new actual request?

**Comment by SidharthBansal** [comment]
Hi all, I missed you all last 2 weeks. I was busy with some important work. Now I am back with my zeal and energy.
@ebarry I will love to take part in the discussion. Can you please share the link?
@jywarren thanks for the comments from twitter. I will be glad to share act of kindness from PL. It is a great mentoring organisation.
@gautamig54 thanks for the awesome checkins.
@alonpeer it will be great if you can help us with some of the PR reviewals and solving some issues related to your stack. It will be really a kind gesture.
@skilfullycurled we will help you out there for sure in a minute. Don't worry. We were all beginners in some part of work at every stage of work. 
Best of luck all the GSoC and Outreachy aspirants for the results. Deadline is over. Still we will be reviewing and commenting suggestions on your proposals so that we can improve the proposals and have a nice workflow. The better and the frequent responses from you the better chances of getting selected at SoC programs.
I will always be giving hints for increasing the chances throughout the timeline.
It is great to see community check-ins are now in rotations as proposed earlier.
What about the mid-monthly video interactions to increase community bonding @jywarren @gauravano @ebarry? Is it on this Monday? Or has it happened?
@gauravano thanks for the rubyme pairing project link. Pairing is a great activity. Remote and driver concept helps to teach the concepts to both mentors and mentee in greater depth. I started rails with pairing projects.

**Goal for this week**
Whitelisting of apps for MK and SWB with the removal of the intermediate gateway page.
Reviewing and assisting all the co-workers at PL. If anyone needs any help then please ping me at the earliest. I will try to help you all as much I can.

**Comment by ebarry** [comment]
@SidharthBansal i have just shared the report document with you to your gmail address ending in 2996 -- looking forward to your comments!

**Comment by ebarry** [comment]
@sagarpreet-chadha and @gauravano i have just shared with both of your gmail addresses ending in 97 also! thank you looking forward to your comments!

**Comment by ebarry** [comment]
Thanks to those who reviewed the Report yesterday, it really advanced significantly and is basically done. I am working on posting it as a Research Note.

**Comment by gauravano** [comment]
Anyone interested in opening next week's check-in?

**Comment by HarshKhandeparkar** [comment]
@gauravano can I do that? I might be a bit late as I will have to it tomorrow night? Or should I do it next week? Doesn't matter to me.

**Comment by gauravano** [comment]
Sure @HarshKhandeparkar! You can open check-in at your own convenience, maybe now, tomorrow night...

Thanks!

**Comment by gauravano** [comment]
Also, how about opening next check-in at https://github.com/publiclab/Leaflet.DistortableImage/? Thanks!

**Comment by HarshKhandeparkar** [comment]
Ok sure. Thanks. I will inform you if I am not able to open a check in this week.

**Comment by sashadev-sky** [comment]
I will open tonight (ie. in like 8 hours) if @HarshKhandeparkar doesn't get to it!

**Comment by HarshKhandeparkar** [comment]
Sorry @gauravano I was very busy travelling. I couldn't open a check in. Sorry for the delay but I completely forgot about this. Apologies

**Comment by HarshKhandeparkar** [comment]
@sashadev-sky you can open the check in. Sorry again.

**Comment by sashadev-sky** [comment]
@HarshKhandeparkar no worries!! Thank you for notifying, i'll open this week 👍

**Comment by sashadev-sky** [comment]
New check-in open in [https://github.com/publiclab/Leaflet.DistortableImage/issues/215](https://github.com/publiclab/Leaflet.DistortableImage/issues/215)

This one can be closed! (I don't have the relevant permissions to do that in this repo)

**Comment by sagarpreet-chadha** [comment]
Awesome , Thank you !!!
