### ISSUE TITLE
Short-code generator for PublicLab.org

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#167]
People on PublicLab.org are embedding maps using these short-codes: https://publiclab.org/inline-maps

A typical shortcode is:

`[map:content:29.9:-90.0]` - showing content near that latitude and longitude

The map it generates is:

![image](https://user-images.githubusercontent.com/24359/57332648-2ca1c180-70e9-11e9-9efe-e6bce1dc6d7d.png)

I'd love to figure out a way to let people select layers that'd be shown by default and help them paste such maps into their posts. Perhaps we can brainstorm how to make this easier, and how to make (still relatively short) shortcodes that have map layers from LEL enabled!

**Comment by sagarpreet-chadha** [comment]
@jywarren ,
how does this regex looks?

**Comment by sagarpreet-chadha** [comment]
https://rubular.com/r/QgZ3aYkOzoTPRS

**Comment by sagarpreet-chadha** [comment]
Solving here: https://github.com/publiclab/plots2/pull/6204
