### ISSUE TITLE
Integration of LBLD into LEL .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#169]
@jywarren ,
Do we have to add LBLD heatmap and other features to each layer of LEL ?

Am i getting this right 🤔  ?  Thanks !

**Comment by jywarren** [comment]
I think we should just choose one way to represent data, and then use it to
make a "public lab people" layer within LEL, and use it on
publiclab.org/people -- what do you think?

**Comment by jywarren** [comment]
That's right! Thanks!

**Comment by sagarpreet-chadha** [comment]
@jywarren , should i commence with this now ? 
I can start with making the PLpeople layer based on the current architecture of the library . What do you think ?

**Comment by jywarren** [comment]
That sounds great!
