### ISSUE TITLE
Planning Issue : Extend leaflet environmental layers

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#173]
**Planning issue for Outreachy project "Extend Leaflet Environmental Layers with new layer menu and layer addition workflow "**

**1) Layer display and UI based issues**
- [x] color coding of layers
- [x] improve structure in the layer selection bar (checkboxes and more info about each layer) #197 #194 
(static template being developed)
- [x] demarcation between layer types (group similar ones under a category etc) #188 
- [x] add meaningful names to base layers

**2) Standardizing Layer code**
- [x] find similarities in code btw layers
- [x] remove redundant code and pass layer type as parameter to a standard layer display code
(common function which could be used to reduce redundant code in layers)
- [x] refactoring based on common functions
- [ ] follow standard methods for each layer like layer.show() layer.hide() layer.isVisible()
   
**3) Documentation**
- [ ] create a template for layer addition
- [ ] document layer addition process 
- [ ] create FTO's for adding new layers after improving documentation

**4) Testing**
- [x] decide on the testing framework (jasmine or other)
- [ ] write tests
- [x] add travis CI ? (discussion req )

**Comment by ananyaarun** [comment]
@jywarren @sagarpreet-chadha @gauravano , here is the planning issue for my project, taken from the discussions here #168

**Comment by gauravano** [comment]
Hi @ananyaarun, sure we'll extend your authority. Also, you can create a project - https://github.com/publiclab/leaflet-environmental-layers/projects/new to manage the workflow once you get permissions. @jywarren also add this repo to https://github.com/orgs/publiclab/teams/soc/repositories. For now, I am adding labels. Not creating a project as you may be interested in doing that yourself (it's cool and easy way to manage :smile:) .

Thanks!

**Comment by sagarpreet-chadha** [comment]
Agreed with Gaurav +1
@ananyaarun awesome :100:

**Comment by sagarpreet-chadha** [comment]
Noting @jywarren comment on revamping architecture https://github.com/publiclab/leaflet-environmental-layers/issues/168#issuecomment-492843352 😄 !

**Comment by ananyaarun** [comment]
@gauravano , I am not able to create a new project, I think it requires permissions ?

**Comment by sagarpreet-chadha** [comment]
Yes it requires permission , lets wait for @jywarren to assign these permissions . Thanks !

**Comment by jywarren** [comment]
OK, i added @ananyaarun -- exciting! Thank you!

**Comment by sagarpreet-chadha** [comment]
Hey @ananyaarun , You can update the checklist above so that i can track your progress 😄 .
Also i think you can start with the second point soon (standardization of layers) . What do you think ?
Thank you !

**Comment by ananyaarun** [comment]
Yes, Even I wanted to start working on standardization of layers. Actually I have a few questions in this regard. Would it be convenient to discuss them with you sometime on gitter before I get started ? Thanks :smiley:

**Comment by sagarpreet-chadha** [comment]
Yes sure, 
Or we can have the discussion in a seperate issue on Github so that people from different places can contribute to the discussion as well . What do you think?

**Comment by ananyaarun** [comment]
Sure, I'll open an issue shortly including the key points to take care of while going about with the standardization. We can discuss there !!

**Comment by jywarren** [comment]
Hi all! I'm closing this as many items are done and the others have been nicely broken out into issues. I'll add one issue for ` follow standard methods for each layer like layer.show() layer.hide() layer.isVisible()` but otherwise, great work!
