### ISSUE TITLE
One liner code to add all layers .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#175]
### Issue :
Currently in `plots2` and `mapknitter` we have to explicitly write code to add each layer which is a cumbersome process especially when we add new layers later in time . 

### Proposed solution :  

Lets give the facility to add all the layers using a single line of code : 

`map123.addAllLayers()` 
or 
`L.layerGroup.addAllLayers().addTo(map123)`

This will eliminate the process to update code in `plots2` and `mapknitter` when any new layer in implemented . 

@jywarren , @ananyaarun What do you think 🤔 ? 

#### Thanks 😄 !

**Comment by ananyaarun** [comment]
@sagarpreet-chadha , sounds great !!
Correct me if i am wrong but,
Does this imply all changes/ newly added layer will be reflected in plots2/mapknitter with one function call like map123.addAllLayers() ?
I'm still trying to understand the integration process and how its working wrt the codebase.
Thanks :)

**Comment by sagarpreet-chadha** [comment]
Yes that is correct :)

**Comment by jywarren** [comment]
This is a cool idea. We could extend this to be something like:

```js
L.EnvironmentalLayers.getAllLayers().addTo(map123); // what do you think of this more specific namespace, by the way? 

// and to take it further:

L.EnvironmentalLayers.getLayers({
  except: ['windrose', 'mapknitter']
}).addTo(map123);

// or:

L.EnvironmentalLayers.getLayers({
  include: ['windrose', 'mapknitter']
}).addTo(map123);
```

This could make the basic constructor for this library quite easy, esp. versus this really long code:

https://github.com/publiclab/plots2/blob/929eb80e7a4b9d2dd628da2657e315dd7cbd57eb/app/assets/javascripts/leaflet_helper.js#L80-L212

How could we make this even simpler so you don't have to individually add all the layers to the layer selector UI?

**Comment by sagarpreet-chadha** [comment]
@ananyaarun and I have discussed the approach in the open call 👍 . We will be focussing on this issue now .

**Comment by jywarren** [comment]
awesome!

**Comment by jywarren** [comment]
#253 could be used to do this!

**Comment by sagarpreet-chadha** [comment]
​0: "purpleLayer"
​​​
1: "toxicReleaseLayer"
​​​
2: "pfasLayer"
​​​
3: "aqicnLayer"
​​​
4: "osmLandfillMineQuarryLayer"
​​​
5: "purpleairmarker"
​​​
6: "skytruth"
​​​
7: "fractracker"
​​​
8: "odorreport"
​​​
9: "mapknitter"
​​​
10: "openaq"
​​​
11: "luftdaten"
​​​
12: "opensense"
​​​
13: "Power"
​​​
14: "Petroleum"
​​​
15: "Telecom"
​​​
16: "Water"
​​​
17: "wisconsin"
​​​
18: "fracTrackerMobile"
​​​
19: "income"
​​​
20: "americanIndian"
​​​
21: "asian"
​​​
22: "black"
​​​
23: "multi"
​​​
24: "hispanic"
​​​
25: "nonWhite"
​​​
26: "white"
​​​
27: "plurality"
​​​
28: "clouds"
​​​
29: "cloudsClassic"
​​​
30: "precipitation"
​​​
31: "precipitationClassic"
​​​
32: "rain"
​​​
33: "rainClassic"
​​​
34: "snow"
​​​
35: "pressure"
​​​
36: "pressureContour"
​​​
37: "temperature"
​​​
38: "wind"
​​​
39: "city"
​​​
