### ISSUE TITLE
Increase layer menu width in layer select dropdown

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#186]
## Description
The current layer menu is too small due to which some of the layer names spill to the next line making the menu crowded
Ex : Indigenous lands territories , indigenous land languages 

![sizebefore](https://user-images.githubusercontent.com/32260628/58042351-16b7e600-7b58-11e9-85a6-f930e3c09a60.png)

## Solution 
- Layer width can be changed to something like 250px from 200px to fit all layers in the same line.
- Shorten layer names a little like indigenous territories and indigenous languages.

**Comment by ananyaarun** [comment]
@sagarpreet-chadha , I opened this as a new issue and changed the previous issues name to keep it as a reference for users of this repo whenever npm install fails :)

**Comment by ananyaarun** [comment]
This is how increasing layer menu width looks like

![lel1](https://user-images.githubusercontent.com/32260628/58305218-e650a000-7e14-11e9-84ad-7a2195563b7f.gif)

**Comment by ananyaarun** [comment]
@sagarpreet-chadha , can I open a PR for this , or is it better to wait for the redundancy issue to be solved, to avoid conflicts in the index.html file ?

**Comment by sagarpreet-chadha** [comment]
Yes lets wait :)
