### ISSUE TITLE
Categorize leaflet environmental layers based on type

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#188]
## Description 
Currently there are too many layers in LEL menu and it needs organization

## Solution
Heading can be added using simple html tags to create a menu like this 

![lel2](https://user-images.githubusercontent.com/32260628/58319348-5e2fc200-7e37-11e9-91a7-111e7d854903.gif)

**Comment by ananyaarun** [comment]
@jywarren @sagarpreet-chadha what do you think ?

**Comment by sagarpreet-chadha** [comment]
Yes great 😄 ! You can start work on this .

**Comment by ananyaarun** [comment]
Sure, I'll start :)
