### ISSUE TITLE
Static HTML mockup of the new "table" Menu in a templates folder

### ISSUE THREAD

**Issue by rarrunategu1** [publiclab/leaflet-environmental-layers#192]
Referenced in https://github.com/publiclab/leaflet-environmental-layers/issues/168

I plan on completing this within the next few days

![image](https://user-images.githubusercontent.com/29240939/58445508-ea0d4c80-80ca-11e9-8371-d20bbf2915f6.png)

**Comment by rarrunategu1** [comment]
@jywarren can you help direct me to where I can get the following picture for the html document? 
![image](https://user-images.githubusercontent.com/29240939/58489923-3b085980-813a-11e9-94b2-4584d7ea5861.png)
I googled and found the rubber boots only.

**Comment by jywarren** [comment]
Ah! I found that at the Noun Project: https://thenounproject.com - Thanks!

**Comment by rarrunategu1** [comment]
Thank you!  I'll send that over in just a couple of minutes.
