### ISSUE TITLE
Add SkyTruth feature .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#2]
More details https://github.com/publiclab/plots2/issues/2427 .

* [x] create a new layer that can be enabled/disabled with http://leafletjs.com/examples/layers-control/
* [x] add a custom icon with http://leafletjs.com/examples/custom-icons/
* [x] make new markers with `L.marker([51.5, -0.09], {icon: greenIcon}).addTo(map).bindPopup("I am a green leaf.");`

Example JSON file for a longitude/latitude box: http://alerts.skytruth.org/json?&d=30&channel=local&l=41.545%2C-71.8331%2C41.8782%2C-71.3524

Here's a broader area: http://alerts.skytruth.org/json?&d=30&channel=local&l=41.042%2C-72.554%2C42.3747%2C-70.6314

**Comment by sagarpreet-chadha** [comment]
@jywarren ...kindly see this 😄 . Thanks !

**Comment by jywarren** [comment]
Oh sorry! This looks great! Thanks!

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren ! 
I have created a **gh-pages** branch and added **node_modules**  folder to it . I do not have the permission to configure the Github Pages .
Can you set the GitHub Pages publishing source to **gh-pages** branch ? 
Thanks !

**Comment by jywarren** [comment]
Actually i think you did it right, you have to add this file when you have a `node_modules` folder for some reason: 

https://github.com/publiclab/leaflet-environmental-layers/blob/gh-pages/.nojekyll

Now it works! https://publiclab.github.io/leaflet-environmental-layers/example/mapSimple.html

**Comment by jywarren** [comment]
This is looking great. I guess we should have some listeners set up at a more complex example (we could put it into `index.html`) that refresh the layers with a new query when you zoom or pan?

**Comment by sagarpreet-chadha** [comment]
There are listeners 😄 !

See this :            https://github.com/publiclab/leaflet-environmental-layers/blob/b6b9f5027e24a5ace84d82cbaab721349d3157fd/src/skyTruthLayer.js#L33

When the map is zoomed / dragged this listener gets called .

And  this : https://github.com/publiclab/leaflet-environmental-layers/blob/b6b9f5027e24a5ace84d82cbaab721349d3157fd/src/skyTruthLayer.js#L39

Removes the marker which is outside the current map-boundary . 

What do you think ?

**Comment by jywarren** [comment]
Oh wow! Maybe it wasn't triggering for the gh-pages demo? Or is it time
bounded and I wasn't seeing latest reports? I tried zooming in but nothing
reloaded. But awesome!!!

**Comment by sagarpreet-chadha** [comment]
Completed in 4744ba246061ebd44ad8918e542564fbf42ee93f .
