### ISSUE TITLE
Add grunt build instructions in readme

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#203]
As of now there are no instructions regarding installing and  running of grunt in readme. 
This command is used to generate the files in /dist folder after making changes in /src folder
Instructions can be added to make this clear to a developer of LEL repo.

**Comment by jywarren** [comment]
This would be super. I think https://github.com/publiclab/image-sequencer/ and
even better https://github.com/publiclab/PublicLab.Editor/#installation has
a nice section you could copy, maybe?
