### ISSUE TITLE
 Lagging of map in full screen due to large parsing of data

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#208]
## Description
In some layers, (like osm ) layer loading takes a lot of time (looks like the browser is hanging ) due to huge data being parsed.
A quick fix would be to allow layer loading only at zoom levels by indicating zoom-in in brackets along with the layer name. 
But a more stable fix is necessary.
 
cc- @jywarren

**Comment by ananyaarun** [comment]
This was fixed temporarily by adding a zoom-in next to layer name in #202 
reference - https://github.com/publiclab/leaflet-environmental-layers/pull/202#pullrequestreview-248532730

**Comment by jywarren** [comment]
I think this can even be a permanent solution! But it might vary by region
- some areas with /much/ more data than others, you know? I'm so glad you
are working on this. Other layers will also need optimization!

Also - this idea that some layers are only enabled at some range of zoom
levels is (as you prob know) another part of the layer standardization
project. That layers could in their basic options have minZoom and maxZoom
bounds. That could be a way to accomplish this too.

**Comment by ananyaarun** [comment]
Sure @jywarren makes sense :)

**Comment by sagarpreet-chadha** [comment]
So restricting heavy data fetching layer to higher zoom level only?

**Comment by jywarren** [comment]
Yes, so adding to the #135 metadata that each layer could optionally provide, would be a zoom range that it'd be enabled!
