### ISSUE TITLE
Bring Base Layers option to bottom of the list .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#21]
We have now 4 base Layers to choose from ---

We need to figure out a way to bring Over Lay layers options to top of the list .

Current scenario : 

<img width="186" alt="screen shot 2018-07-01 at 12 13 54 pm" src="https://user-images.githubusercontent.com/14952645/42131800-4862dc5c-7d28-11e8-8165-e3cb7bafbbd1.png">

**Comment by dewanhimanshu** [comment]
can you assign this issue to me

**Comment by sagarpreet-chadha** [comment]
Solved by @dewanhimanshu in PR #29 .
