### ISSUE TITLE
Workflow for managing dist files

### ISSUE THREAD

**Issue by ananyaarun** [publiclab/leaflet-environmental-layers#218]
# Description
Currently dist file are not in gitignore and hence huge lines of change needs to be merged in each PR. This leads to conflicts in dist files in other PR's etc. Dist files workflow are not very clear to a  new comers and they usually get stuck with the grunt build step.

# Solution
We can add dist to .gitignore
This has been done in IS repo here https://github.com/publiclab/image-sequencer/pull/908

cc @sagarpreet-chadha @jywarren

**Comment by jywarren** [comment]
Oops, did we start gitignoring the .css files too? Yes, but we didn't stop tracking them. So, for some reason we aren't seeing `dist` files from NPM anymore. Huh? Let me look, maybe npm is reading our gitignore?

**Comment by jywarren** [comment]
Oops! 

> Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.

So, ok i will override in this way. Opening a PR.

**Comment by jywarren** [comment]
https://github.com/publiclab/leaflet-environmental-layers/pull/228
