### ISSUE TITLE
Error in latest main branch on windrose layer ajax call

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#220]
Hi, all -- i'm trying to release some additional tweaks to the MapKnitter layer in #219 -- but seeing this error:

```

(index):89 GET http://localhost:3001/lib/leaflet-environmental-layers/dist/windRoseLayer.js net::ERR_ABORTED 404 (Not Found)
LeafletEnvironmentalLayers.js:12112 Uncaught TypeError: Cannot read property '_leaflet_id' of undefined
    at stamp (LeafletEnvironmentalLayers.js:12112)
    at NewClass.getLayerId (LeafletEnvironmentalLayers.js:18842)
    at NewClass.addLayer (LeafletEnvironmentalLayers.js:18735)
    at NewClass.addMarker (LeafletEnvironmentalLayers.js:26644)
    at NewClass.parseData (LeafletEnvironmentalLayers.js:26652)
    at Object.success (LeafletEnvironmentalLayers.js:26600)
    at fire (jquery.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1:3292)
    at Object.fireWith [as resolveWith] (jquery.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1:3422)
    at done (jquery.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1:9534)
    at XMLHttpRequest.<anonymous> (jquery.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1:9786)
```

Note that in the MK code (in https://github.com/publiclab/mapknitter/pull/775) we are only showing the MK layer, so I wonder if we're making an assumption that the windrose layer will be there? 

@ananyaarun @sagarpreet-chadha I'm hoping this will get featured in tomorrow's release of MapKnitter 3.0, so if you have a moment to take a look that would be great! Thank you!

**Comment by ananyaarun** [comment]
Ok looking at it @jywarren

**Comment by jywarren** [comment]
Thanks!!! This is being seen downstream as well: https://github.com/publiclab/plots2/pull/5971#issuecomment-507528597

This is a great rehearsal for publishing new versions later! It's nice to see that `plots2` will also help us catch such errors 😄

**Comment by ananyaarun** [comment]
Hey, so as you said in the call today, basically there are no tests for this layer yet in LEL.
But I guess this broke some test during the integration process.

I'm figuring out writing tests. I'll start with the indigenous layers and once I'm done with that perhaps other layers will be easy.
cc @jywarren

**Comment by jywarren** [comment]
Awesome!

**Comment by sagarpreet-chadha** [comment]
Hey!
I think it is now solved in the last PR by me . As the windrose.js file was moved from /dist folder to /src folder via some FTO so we needed to change the URL of script file in plots2 . Thanks :)

**Comment by jywarren** [comment]
Hi, ok, thanks! Does this mean we no longer need to individually include it?

**Comment by jywarren** [comment]
OK, i think i got the windrose one resolved by changing it's path from 'dist' to 'src'.

But I'm still seeing this error in the `stamp()` method, which seems to be part of Leaflet?

```
LeafletEnvironmentalLayers.js:12112 Uncaught TypeError: Cannot read property '_leaflet_id' of undefined
    at stamp (LeafletEnvironmentalLayers.js:12112)
    at NewClass.getLayerId (LeafletEnvironmentalLayers.js:18842)
```

It all begins at this line:

`  var MapKnitter = L.layerGroup.mapKnitterLayer().addTo(Mapknitterunique);`

here: 

https://github.com/publiclab/mapknitter/blob/40e21153fba5ed98bca2cc423e00885420158784/app/views/front_ui/index.html.erb#L267

**Comment by jywarren** [comment]
Hmm, i'm really struggling with this @sagarpreet-chadha @ananyaarun can you see what's going wrong?

**Comment by jywarren** [comment]
In local testing, the mapknitter layer loads. But i see the error and so the spinner never stops:

![image](https://user-images.githubusercontent.com/24359/60738772-7eba6400-9f2d-11e9-8377-205f3baf4984.png)

**Comment by jywarren** [comment]
It looks like we're getting a `null` passed out of this function:

```js

              var mapknitter ;
              if (!isNaN(lat) && !isNaN(lng) ){
                if (image_url !== undefined){
                  mapknitter = L.marker([lat , lng] , {icon: redDotIcon}).bindPopup(
                    "<div class='mapknitter-info'><h4>"+ "<a href=" + map_page + ">" + title + "</a></h4>" + 
                    "<p>by " + "<a href=" + url + ">" + author + "</a>" + 
                    " near " + location  + 
                    "</p><a href=" + map_page + "><img src="+image_url+" style='width: 245px;'></a></div>"
                  ) ;
                }
              }
```

**Comment by jywarren** [comment]
I see. I introduced code to check if there's an image. But now if there is no image, it passes back a null layer. Let's be sure it checks ahead of time and stops trying to make a layer. This was my fault, sorry!

**Comment by jywarren** [comment]
Testing `v1.3.3` now!

**Comment by jywarren** [comment]
Gah! @sagarpreet-chadha @ananyaarun my apologies, i forgot the dist files need to be built before publishing on NPM now. Doing that as `v1.3.4`!

**Comment by jywarren** [comment]
Wait, something more complex is going on. Moving to https://github.com/publiclab/leaflet-environmental-layers/issues/218

**Comment by jywarren** [comment]
Resolved!

**Comment by ananyaarun** [comment]
Great !!
