### ISSUE TITLE
Default to current layers in fullhash

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#221]
This relates to #33 #86 but I noticed that if we redirect to a URL like `mapknitter.org#6/44/-90/`, we get an error because we haven't specified a layer, in https://github.com/publiclab/mapknitter/pull/775 -- and I will add the layer name but wanted to change this behavior so it defaults to whatever layer is currently shown... can that work? @sagarpreet-chadha @ananyaarun 

https://publiclab.github.io/leaflet-environmental-layers/example/#3/43.00/-52.77/BL2-MapK

(demo of fullhash)

Thank you!

**Comment by sagarpreet-chadha** [comment]
Hi @jywarren ,
Sorry i didn't get exactly the issue here 😃.

**Comment by jywarren** [comment]
Ah I see, I think the key here is for it to not error when changing the hash, and I think I found some bugs when not specifying a layer. Could you try this out both opening a url with no layer specified and also changing the hash in the same tab, to see if we are getting any errors, esp when a layer is not specified in the hash? Thanks!

**Comment by SidharthBansal** [comment]
Can we have this in GCI @jywarren @sagarpreet-chadha @ananyaarun ?

**Comment by jywarren** [comment]
I think this is solved... both https://publiclab.org/maps#3/41.00/-71.00/ and https://mapknitter.org/#9/41.8082/-71.4262/ seem to be working fine!
