### ISSUE TITLE
Unable to see marker popups on publiclab.org/people map

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#249]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

I visited https://publiclab.org/people#5/37.533/-108.714/BL1 but got this JS console error when clicking markers:

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at NewClass._updateContent (LeafletEnvironmentalLayers.js:21428)
    at NewClass.update (LeafletEnvironmentalLayers.js:21371)
    at NewClass.onAdd (LeafletEnvironmentalLayers.js:21308)
    at NewClass.onAdd (LeafletEnvironmentalLayers.js:21562)
    at NewClass._layerAdd (LeafletEnvironmentalLayers.js:18527)
    at NewClass.whenReady (LeafletEnvironmentalLayers.js:16407)
    at NewClass.addLayer (LeafletEnvironmentalLayers.js:18589)
    at NewClass.openPopup (LeafletEnvironmentalLayers.js:21785)
    at NewClass.openPopup (LeafletEnvironmentalLayers.js:21893)
    at NewClass._openPopup (LeafletEnvironmentalLayers.js:21968)
```

Maybe we need to merge https://github.com/publiclab/plots2/issues/5874 to solve this? cc @sagarpreet-chadha thank you!

**Comment by sagarpreet-chadha** [comment]
continued from https://github.com/publiclab/plots2/pull/6204


I have made PR in `leaflet` repository: https://github.com/Leaflet/Leaflet/issues/6840
Let's wait for their response :)
Else we can fork out from Leaflet and use that repo!

<img width="426" alt="Screenshot 2019-10-06 at 2 17 14 PM" src="https://user-images.githubusercontent.com/14952645/66717608-7c06bf00-edf8-11e9-8cb9-51e69376d809.png">

**Comment by SidharthBansal** [comment]
Can we have this in GCI @jywarren @sagarpreet-chadha @ananyaarun ?

**Comment by jywarren** [comment]
Yes please! cc @crisner @nstjean as well! As you two learn more about LEL,
GCI can be a good place to recruit help from!

**Comment by SidharthBansal** [comment]
Hi @crisner and @nstjean are you willing to be GCI mentors? If yes then please ping me at bansal.sidharthcode@gmail.com.
Thanks

**Comment by SidharthBansal** [comment]
Published to GCI dashboard

**Comment by sagarpreet-chadha** [comment]
Hey this is solved! @jywarren , i have made some changes in LEL to solve this. It is live, you can verify. 

@SidharthBansal , let's remove this from GCI.
