### ISSUE TITLE
Datasource: finding fires from space on eosdis.nasa.gov

### ISSUE THREAD

**Issue by ebarry** [publiclab/leaflet-environmental-layers#250]
https://firms.modaps.eosdis.nasa.gov/map/ – finding fires from space

**Comment by crisner** [comment]
Hi! I am an Outreachy applicant and I would like to contribute to this project. Is this issue to add a new layer that displays markers on locations with fires? I would like to know if I can work on this as an Outreachy applicant.

**Comment by sagarpreet-chadha** [comment]
Yes please go ahead :)

**Comment by crisner** [comment]
Thank you! Shall begin working on this.

**Comment by crisner** [comment]
@sagarpreet-chadha @ebarry I was wondering if I can use the data for fires from [https://eonet.sci.gsfc.nasa.gov/](https://eonet.sci.gsfc.nasa.gov/)? They have provided an api that lists events into a json format. I am haven't used wms before but the 'FIRMS' data seems to give back a single image and not coordinates.

**Comment by crisner** [comment]
Please review my PR and let me know of any changes that need to be done. Thanks!
