### ISSUE TITLE
allow 'exclude' param in one-line constructor

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#257]
As follow-up to https://github.com/publiclab/leaflet-environmental-layers/issues/175, I'd like to be able to `exclude` layers, which means showing ALL layers except those excluded. This would be a good chance to update our README too, with:

```md
## Setup

To simply add layers to a Leaflet map, be sure you have the needed dependencies installed (see Dependencies, below) for the layers you want, then use the following constructor function to add them:

```js
L.LayerGroup.EnvironmentalLayers({
  include: ['mapknitter', 'clouds'],
  hash: true,
}).addTo(map);
```

See this in action in the example: https://github.com/publiclab/leaflet-environmental-layers/blob/master/example/oneLinerCodeExample.html#L66-L69

Alternatively, you can provide an `exclude` parameter, and it will show all layers except those you specify. 

How does this sound?

**Comment by sagarpreet-chadha** [comment]
Hi Jeff, this is already implemented :)
Will be updating the Readme soon . Thanks!

**Comment by jywarren** [comment]
Awesome!!! Yes, just wanted to know the exact syntax!
