### ISSUE TITLE
Help spread out markers that overlap (with a plugin)

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#258]
https://github.com/jawj/OverlappingMarkerSpiderfier-Leaflet does this nicely!

http://jawj.github.io/OverlappingMarkerSpiderfier-Leaflet/demo.html

![image](https://user-images.githubusercontent.com/24359/64738102-5ebe9800-d4bc-11e9-9dfb-45e3a71b652b.png)

**Comment by crisner** [comment]
Hi @jywarren! I am Outreachy applicant. Can I work on this?

**Comment by sagarpreet-chadha** [comment]
Go ahead :)

**Comment by crisner** [comment]
Thank you! :D
