### ISSUE TITLE
Planning: Mapping tasks in plots2 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#274]
**Visit a wiki page and see an embedded map in the page content**

* Which wiki page? Is this flow for existing wiki-pages? -- example: https://publiclab.org/wiki/one-cranston

> the map has some layers pre-selected and visible

* pre-selected layers are only present if we use the new inline map syntax, right?
  -- yes! 

> the map has a prompt button (implemented in plots as in this example); clicking it opens a new post with a template (?n=X) and pre-set lat/lon location pulled from the map's current center

*  prompt button should be on map? Can you share a mock-up please?
* Can you please share the screenshot of this existing prompt and steps to reproduce this?
 -- see https://publiclab.org/wiki/coqui#Coqui+versions -- screenshot:

![image](https://user-images.githubusercontent.com/24359/67811858-17906480-fa74-11e9-8cd2-0641b70166c6.png)

> clicking on PL post markers on the map shows the lead image of the marker, the title, author, and a "read more" button

> the map may be expanded to become full screen, with a box icon

> maps can display posts from PL in addition to layers

we have to implement a separate layer in LEL for this? - yes, i think so!

****

### Less urgent:

> the form is based on the new simplified form mockups

* Which mock-up? -- https://publiclab.org/notes/warren/09-23-2019/improved-smartphone-friendly-posting-form-designs-feedback-welcome

> the map has a button offering it's own <iframe> code so that it may be embedded (as other grids do)

* can you share the code and url of how this looks on PL.org for grids? -- yep, as here, [code here](https://github.com/publiclab/plots2/blob/dfc153da7a93deb3cdb35f3a4d56e5518f82a45c/app/views/grids/_notes.html.erb#L113-L115):

![Untitled](https://user-images.githubusercontent.com/24359/67811983-57efe280-fa74-11e9-9669-d84e098ee294.png)

**Comment by sagarpreet-chadha** [comment]
**Create a wiki page with an embedded map** 

* How do we create the embedded map? The new inline map for LEL layers, right?
* Or are we talking about the /post page (where we create content)?

> the map has some layers pre-selected and visible


> the prompt button's text is configurable (perhaps the button is separate, but is a new inline powertag like [button:map:Text here] ?)

* More details where, which page are we talking here?

> the prompt button uses an onClick JS handler to function, and first fetches the correct map's center and constructs a URL appropriately with format "?tags=lat:1.0000,lon:1.0000"

> the prompt button and the wiki work even when multiple are embedded on the same page (unique map id, unique variable names)

This prompt button does this job:  clicking it opens a new post with a template (?n=X) and pre-set lat/lon location pulled from the map's current center

**Comment by sagarpreet-chadha** [comment]
I would get more idea about these features if you can share what we wish to do here from the perspective of user? Thanks @jywarren 😄

**Comment by jywarren** [comment]
Hi! Thanks, just did this by editing above. I also organized the most urgent at top, and the less urgent below! I hope that helps!

**Comment by jywarren** [comment]
Above - `maps can display posts from PL in addition to layers` -- the idea is that the prompt button will open a post form bearing tags which will then generate a new marker in the inline map, once posted. It's a button to "add a post that'll appear in this map" essentially, does that make sense?

**Comment by jywarren** [comment]
However, I think there may be a way to do it without making a new LEL layer... for starters. Because posts already appear in inline maps: https://publiclab.org/wiki/inline-maps

Later, we could circle back and re-implement it as a unique layer.

**Comment by sagarpreet-chadha** [comment]
Hey @jywarren ,

I think we would not be able to make an inline syntax to make a button because we do not have map id to link that button to the map because map id is generated randomly, hence I am thinking of adding a line like to inline maps (having **content and tags** in their syntax):

Prototype 1

<img width="873" alt="Screenshot 2019-11-01 at 5 56 41 PM" src="https://user-images.githubusercontent.com/14952645/68024828-3ccdde80-fcd1-11e9-9874-8920c3f43fb4.png">

Or something like this which will appear on the map : I think this feels like a part of the map and more intuitive to use maybe.

Prototype 2

<img width="858" alt="Screenshot 2019-11-01 at 5 57 00 PM" src="https://user-images.githubusercontent.com/14952645/68024893-625ae800-fcd1-11e9-80fe-622e6212713d.png">


Which one looks better? 


Also, just to confirm -- on clicking this link we have to open a new /post page which has tags lat:XX and lon:XX calculated from that maps center and added automatically, right?

Thanks!

**Comment by jywarren** [comment]
That's right, but cant we make the link use btn-primary css and appear as a
button?

The first one looks great for a first version! Thanks Sagarpreet!

**Comment by sagarpreet-chadha** [comment]
Yes we can use a button.

So if there are multiple maps on the page, we want that button for each map?

Also, just to confirm -- on clicking this link we have to open a new /post page which has tags lat:XX and lon:XX calculated from that maps center and added automatically, right?

Thanks!

**Comment by jywarren** [comment]
Yes on both! Thanks!

**Comment by sagarpreet-chadha** [comment]
Making a new route for full screen map:

**Comment by sagarpreet-chadha** [comment]
http://localhost:3000/fullscreenMap/Unearthing,asian,eonetFiresLayer/23.12321/77.23432/11.65432

**Comment by jywarren** [comment]
This is awesome! Can we have the path be /map and use only url hashes
instead of parameters? That way we can rewrite them in JavaScript without
reloading the page!

**Comment by jywarren** [comment]
https://github.com/publiclab/image-sequencer/blob/main/examples/lib/urlHash.js

**Comment by sagarpreet-chadha** [comment]
Okay

**Comment by jywarren** [comment]
I think we're done here! Thank you!!!

**Comment by sagarpreet-chadha** [comment]
🎉
