### ISSUE TITLE
Unearthing layer showing grey dots instead of blue in Chrome on Mac

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#286]
Hi, it looks like there is some error with the Unearthing layer on plots2 -- I'd love some help debugging this, @sagarpreet-chadha ! Thank you!

https://publiclab.org/wiki/sandbox-3#Unearthing+layer

**Comment by jywarren** [comment]
Hi, it looks like it's showing now!

**Comment by jywarren** [comment]
Re-opening - i'm not sure why but the markers are showing up grey - with blue borders. Maybe we need to compare to the original PR? 

https://github.com/publiclab/leaflet-environmental-layers/pull/283 vs
https://github.com/publiclab/leaflet-environmental-layers/pull/279

@sagarpreet-chadha no rush but is it possible to look at this? Because I want to modify this layer to show open vs. no-longer-operating points. Thanks!

**Comment by jywarren** [comment]
https://github.com/publiclab/leaflet-environmental-layers/blob/392cebc64050bb5f65e0c76ccd1700336be1ef25/src/unearthing.js#L43

**Comment by SidharthBansal** [comment]
Can we have this in GCI @jywarren @sagarpreet-chadha @ananyaarun ?

**Comment by jywarren** [comment]
I'd like to solve this earlier, but if it's still not solved by then, then sure!

**Comment by sagarpreet-chadha** [comment]
@jywarren , What exactly is the problem? 
I see 2 types of dots - green and bluish-purple . Thanks!

**Comment by jywarren** [comment]
Oh it's so strange, I see it correctly on my phone, but on my computer I see the dots grey with a blue outline for the unearthing layer. Maybe it's something cached... I will try flushing the cache!

![Screenshot_20191128-111041](https://user-images.githubusercontent.com/24359/69820760-dce32e80-11cf-11ea-9267-d20275e38d96.png)

This screenshot is correct, thanks!

**Comment by jywarren** [comment]
Strangely it seems to be going back and forth - on Chrome on Mac i see grey:

![Screen Shot 2019-12-03 at 9 44 45 AM](https://user-images.githubusercontent.com/24359/70072993-177d0a80-15c6-11ea-8cb4-b389da809579.png)

Even after clearing my cache!

**Comment by jywarren** [comment]
So strange. In Firefox it works fine:

![image](https://user-images.githubusercontent.com/24359/70081537-c32e5680-15d6-11ea-9df2-143dac60de93.png)

So, this seems to be purely a Chrome on Mac issue, while Chrome on Android or Firefox on Mac both work...

**Comment by nstjean** [comment]
Looks correct on Chrome on Ubuntu.

**Comment by chen-robert** [comment]
I'm seeing blue dots on Chrome on Windows 10.

**Comment by jywarren** [comment]
Confirmed on Mac Chrome on another machine they appear blue. I guess I give up... closing this as my computer seems to be the only one affected!

<img width="1253" alt="Screen Shot 2019-12-04 at 10 52 27 AM" src="https://user-images.githubusercontent.com/24359/70157986-7b660880-1684-11ea-98f7-097b4c031c06.png">

Thanks all!
