### ISSUE TITLE
Add ToxicRelease Layer .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#3]
### Discussion : 
 * the Toxic Release Inventory: https://publiclab.org/q/15653

### API link : 
*  url: https://iaspub.epa.gov/enviro/efservice/tri_facility/pref_latitude/BEGINNING/41/rows/0:100/JSON

### Marker (green color) : 
* url: http://www.clker.com/cliparts/r/M/L/o/R/i/green-dot.svg',

**Comment by sagarpreet-chadha** [comment]
API link is not working now !

**Comment by jywarren** [comment]
wait, this one? https://iaspub.epa.gov/enviro/efservice/tri_facility/pref_latitude/BEGINNING/41/rows/0:100/JSON

It seems to be working for me just now... can you try again?

**Comment by sagarpreet-chadha** [comment]
Yes it is working now . On it 👍 !

**Comment by sagarpreet-chadha** [comment]
Completed in 9552bf92ee6eae1f1f57d1f94237b66058fd2199 .

**Comment by sagarpreet-chadha** [comment]
PR #8 .
