### ISSUE TITLE
Make code formatting consistent across files

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#301]
Presently, the code has different formatting styles. The code needs to follow the styles listed below for consistency and clarity across all files,
- two spaces for indents
- brackets in `if` statements for clarity

**Comment by crisner** [comment]
@jywarren, anything else you would like to add? What about the spaces between the brackets in `if` statements? In some places, there are no spaces between brackets. Do you have a particular style guide in mind?

**Comment by jywarren** [comment]
If you'd like to use what we use in other PL repos, maybe we should look at
https://github.com/publiclab/Leaflet.DistortableImage/ and, um,
ask @sashadev-sky or @rexagod if they're available? There are some
automated ways to do this too!

**Comment by crisner** [comment]
Thanks! Shall take a look at it. Yes, I was looking into prettier and beautifier to use as a grunt task.

**Comment by crisner** [comment]
@sashadev-sky and @rexagod, any suggestions regarding style guides, preferably ones that are commonly used in other PL repos?

**Comment by crisner** [comment]
Leaflet.DistortableImage uses the ESLint config for the Google JavaScript style guide. I shall follow the same here in LEL.

**Comment by rexagod** [comment]
Apologies for the late response, Renisha! I'm okay with your decision to follow the same guide used in LDI here in LEL. Go ahead!

**Comment by crisner** [comment]
Thanks @rexagod!
