### ISSUE TITLE
Infinite Loading at PurpleAirLayer-HeatMap

### ISSUE THREAD

**Issue by CodeSarthak** [publiclab/leaflet-environmental-layers#302]
When I try to select PurpleAirLayer - HeatMap, I only see an infinite loading circle, as shown here : 

![image](https://user-images.githubusercontent.com/24937677/70821444-15564f80-1e01-11ea-8b7e-a66e4056bdce.png)

**Comment by gabrielrumiranda** [comment]
Hi @CodeSarthak recently PurpleAirLayer - HeatMap was with bug, but i fixed in #295, and now is merged and fix

**Comment by CodeSarthak** [comment]
Good job @gabrielrumiranda 👍 

Resolved by #295
