### ISSUE TITLE
Add documentation for testing the repo

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/leaflet-environmental-layers#323]
In many of our other publiclab repos, there is extensive documentation on how to correctly test the codebase.
In LEL, it is very difficult for someone not acquainted with the tech stack or the code itself to run the tests.
For example, if a user runs `npm test`, the command executed is:
`echo \"Error: no test specified\" && exit 1`.
This just returns an error but doesn't give the user any information on how he can actually specify a test to have it run. Instead we could link to our documentation with a proper gem.
 
What do you think? @publiclab/mapknitter-reviewers? 
Is this a good idea?

**Comment by cesswairimu** [comment]
Hey @Uzay-G, I think this was an amazing issue...I was just wondering why you closed it...Thanks

**Comment by Uzay-G** [comment]
Well, this is a bit embarassing but this issue was for the Leaflet.DistortableImage repo and I posted it in the wrong one. That's why I closed this one and opened it on on LDI. :smile:

**Comment by cesswairimu** [comment]
hahaha :laughing: no worries, happens when you are working on a couple of repos. Thanks
