### ISSUE TITLE
ability to generate permalink with url hash of currently enabled layers

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#33]
This could be long, so not displayed as a default but via a link icon maybe?

**Comment by jywarren** [comment]
@sagarpreet-chadha what do you think of this one? Maybe we could just use a unique index like 0,1,2 for layers...

**Comment by jywarren** [comment]
So then `url.com/#l=1,4,5,6`

**Comment by sagarpreet-chadha** [comment]
Hi !
Leaflet-Hash do not support active layers in url . (Although many people want this !)
 So this is kind of tricky as i may have to extend the Leaflet-Hash library functionality . 

I am thinking of writing the code not as apart of library's functionality , (Maybe we can make a separate library later on) AND writing the JS code in `index.html` for now .

Steps : 
1.) Getting the url from browser . 
2.) Using REGEX to calculate layer number and storing them to params maybe .
3.) Looping over layers and adding corresponding  TileLayer variable and making an array of such  variables .
4.) Passing this array when we initialize the map .

5.) [ Important ]  Making Logic to dynamically change the URL when a new layer is added / removed . 

What do you think ?

**Comment by jywarren** [comment]
would this be able to not interfere with leaflet-hash? If that's simpler,
maybe it could make a good first step towards a more integrated (with
leaflet-hash) solution, what do you think?

**Comment by sagarpreet-chadha** [comment]
Found this plugin https://github.com/KoGor/leaflet-fullHash !
Will try to use it , although it does not has cdn link and is not present on npm as well .

**Comment by jywarren** [comment]
oh goodness, i realized this after leaving comments. LOL (LEL lol)

ok, so what you can do is actually fork it and make a release in your fork,
and use this syntax to include it in package.json, right?

"inline-markdown-editor": "publiclab/inline-markdown-editor#~0.3.0",
