### ISSUE TITLE
Skytruth popup improvements

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#336]
Let's get some more of the data from SkyTruth Alerts into the popups for this layer!

![image](https://user-images.githubusercontent.com/24359/72011473-f0020900-3227-11ea-8d59-c8ed3ee757e1.png)

cc @crisner @sagarpreet-chadha just to put this on your radar... maybe this could make a good FTO?

Connecting also to #118

**Comment by jywarren** [comment]
https://alerts1.skytruth.org/report/e3386004-2fa4-39cc-9003-820a3e775b1d#c=json

https://publiclab.github.io/leaflet-environmental-layers/example/#lat=40.1070&lon=-75.6732&zoom=14&layers=Standard,fracTrackerMobile,skytruth,fractracker,toxicReleaseLayer,mapknitter,Power,Petroleum,Water

**Comment by crisner** [comment]
Yes, looks like it could make a good FTO!
