### ISSUE TITLE
Embed code URL has duplicated text

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#338]
It looks like it says `leaflet-environmental-layers` twice in the demo. But otherwise great!

![image](https://user-images.githubusercontent.com/24359/72011907-c9909d80-3228-11ea-8852-571d68d8ceda.png)

https://publiclab.github.io/leaflet-environmental-layers/example/#lat=40.1070&lon=-75.6732&zoom=14&layers=Standard,fracTrackerMobile,skytruth,fractracker,toxicReleaseLayer,mapknitter,Power,Petroleum,Water

**Comment by crisner** [comment]
I'll work on this. I wonder why the tests didn't pick this up. I will have to look at the spec files too.
