### ISSUE TITLE
Add media queries for layers menu for screen size 235x300

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#344]
The current layers browser menu does not fit well in the map displayed on the sidebar in publiclab.org. On examining, the container size seems to be at 235x300 but the menu is responsive only up to 320. Once this is addressed we can implement the new layers menu in plots2.

Because of the small screen size, it would be better to hide all information other than layer names and their selection controls.

**Comment by crisner** [comment]
@jywarren and @sagarpreet-chadha, would like your thoughts on this. Thanks!

**Comment by jywarren** [comment]
I think this is right, yes! The only other alternative is to make the subsections collapsible somehow so you can expand them by pressing a small icon or link. But let's start with something basic like just hiding them, yeah!

**Comment by crisner** [comment]
Awesome. I am adding this to my list for this week.

**Comment by sagarpreet-chadha** [comment]
Yes hiding seems perfect first start to approach this!
