### ISSUE TITLE
layersBrowser default layers objects

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-environmental-layers#362]
Currently to have the new layersBrowser menu included in a map you have to specify a list of all the layers:

https://github.com/publiclab/leaflet-environmental-layers/blob/7cf1aa1b19e9b3728901465255d13ab3f028a786/example/layers.js#L117-L198

https://github.com/publiclab/leaflet-environmental-layers/blob/7cf1aa1b19e9b3728901465255d13ab3f028a786/example/layers.js#L262-L263

I think these default layer lists should be moved into layersBrowser.js, with just options being passed in. Then by default all the layers would be displayed on the menu.

@crisner What do you think?

**Comment by nstjean** [comment]
Wait, I see you just implemented this! https://github.com/publiclab/leaflet-environmental-layers/pull/353 This is perfect. So I'm assuming once LEL version gets updated on plots2 we can use this new code!

**Comment by crisner** [comment]
The code that is used in plots2 is from `AllLayers.js`. It was already implemented for the default layer control. I updated it to be used with the implementation of the new menu as well. This doesn't change the code in `layers.js` though.

**Comment by nstjean** [comment]
Okay. That's why I was confused at first, but I see the changes to `AllLayers.js` and how it will all work.
