### ISSUE TITLE
Fix duplication of jquery script tags

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#372]
Some layers seem to be creating a script tag with jquery('https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js') as its source and this is being appended to the head of the HTML file the source lives in. This seems to be creating a conflict here in plots2 just as the mapDependencies did. Here are the lines from one of the layers:
https://github.com/publiclab/leaflet-environmental-layers/blob/c69ad9a84b99734dc394b9ad34b6c23b3b67fb47/src/pfasLayer.js#L44-L46

Addressing this issue would solve the jquery related errors popping up in pages that contain maps.

The layers that create a new script tag for jquery are:
- pfasLayer.js
- toxicReleaseLayer.js
- osmLandfillMineQuarryLayer.js
- googleSpreadsheetLayer.js

_Originally posted by @crisner in https://github.com/publiclab/plots2/issues/7381#issuecomment-580131418_

Digging into LEL code...
The error happens on this line:
https://github.com/publiclab/leaflet-environmental-layers/blob/c69ad9a84b99734dc394b9ad34b6c23b3b67fb47/src/AllLayers.js#L220
And specifically only with toxicReleaseLayer (so far that I can tell) and only when it is on the screen. If that layer triggers whatever-it-is error, then no other maps will work right either, including sidebar maps.

![🎈 Public Lab: Switzerland Fires - Google Chrome_031](https://user-images.githubusercontent.com/49460529/73394673-0857c780-42ac-11ea-9e72-b9a505f5c17d.png)

![🎈 Public Lab: Switzerland Fires - Google Chrome_032](https://user-images.githubusercontent.com/49460529/73394682-0d1c7b80-42ac-11ea-8f82-b5e6b9667be5.png)

![🎈 Public Lab: Switzerland Fires - Google Chrome_034](https://user-images.githubusercontent.com/49460529/73394695-11e12f80-42ac-11ea-829e-9e060bbf44db.png)

I will take a look at why that particular layer is different from the others.

_Originally posted by @nstjean in https://github.com/publiclab/plots2/issues/7381#issuecomment-579945120_

**Comment by crisner** [comment]
![script-error](https://user-images.githubusercontent.com/29401459/73447807-82a84a80-4385-11ea-9029-54ee85f8da5f.png)

**Comment by nstjean** [comment]
Nice catch!! I think we do need to address this in LEL like you posted.

Why are layers adding dependencies anyways? Shouldn't that be something that is added globally in LEL? We'd still have to do the check if it already existed, but I feel like it shouldn't be something that the layers themselves are doing.

_Originally posted by @nstjean in https://github.com/publiclab/plots2/issues/7381#issuecomment-580262057_
