### ISSUE TITLE
Fix missing layers in layer menu on refresh

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#374]
There was a change I made on one of my previous PRs that fixed some errors by adding a check to when the 'moveend' event was triggered. This seems to have affected how the layers were displayed in the layers menu when the page was refreshed. Sometimes there were layers missing from the layers menu when it should have been there.

https://github.com/publiclab/leaflet-environmental-layers/blob/c69ad9a84b99734dc394b9ad34b6c23b3b67fb47/src/util/layersBrowser.js#L470-L477

**Comment by jywarren** [comment]
Ah, is it possible this was related to https://github.com/publiclab/leaflet-environmental-layers/issues/376 ?Thank you!

**Comment by crisner** [comment]
This was not implemented into the one-liner usage in the version used in plots2. Also, this deals with overlays and does not affect baselayers. 😃
