### ISSUE TITLE
Default baselayer not loading properly on inline maps

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-environmental-layers#376]
On plots2 I am removing references to baselayer so that we can just use the default LEL baselayer for now. I've noticed that pages with just one map (like /map/) load the baselayer properly, however inline maps, especially on pages with multiple maps, are not showing things correctly:

![FireShot Capture 256 - 🎈 Public Lab_ Inline Maps - localhost](https://user-images.githubusercontent.com/49460529/73475100-b3748980-435d-11ea-88cc-00f51e1e9eb8.png)

We didn't notice this before because it was saving a custom basemap overtop of the default.

**Comment by crisner** [comment]
For now passing the initialized baselayer through the options should work. Just initializing it outside without passing it in would not work as it would get replaced by the default baselayer.

**Comment by crisner** [comment]
But if it works here then the change sounds good.

**Comment by nstjean** [comment]
I was noticing one issue on some maps with the default being displayed overtop of the passed-in baselayer:

![FireShot Capture 258 - 🎈 Public Lab_ Inline Maps - localhost](https://user-images.githubusercontent.com/49460529/73478956-00a82980-4365-11ea-89c3-91c595801880.png)

**Comment by nstjean** [comment]
I copied and pasted over the newest version of dist/LeafletEnvironmentalLayers.js to test it out and I think you're right, the newest changes you made should hopefully solve this issue.

**Comment by jywarren** [comment]
Awesome, thanks @crisner for responding to https://github.com/publiclab/plots2/issues/7397 and linking it to here. I'll close that one. Thanks!

**Comment by jywarren** [comment]
And, let's think of ways to add tests for some of these cases both on LEL and plots2!

**Comment by crisner** [comment]
Yes. LEL does not have many tests. Once I finish the issues in progress I'll focus on writing some tests to check if maps work as expected on a page.

**Comment by nstjean** [comment]
Yes definitely. We need some in LEL for inline maps and the /map/ page, probably /people/ too.

**Comment by nstjean** [comment]
This appears to be fixed now with the LEL 2.2.1.
