### ISSUE TITLE
Add a changelog to keep track of changes

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#388]
Add a changelog file that we can keep updated as we make new changes so we know what we can know the changes done for each version when publishing LEL.

**Comment by sagarpreet-chadha** [comment]
We should use https://github.com/publiclab/leaflet-environmental-layers/releases .
I am drafting new release, @crisner or @nstjean can you guy update this release and add all the changes in `version 2.2.1 ` . Thanks!

https://github.com/publiclab/leaflet-environmental-layers/releases/tag/2.2.1

**Comment by crisner** [comment]
Did you mean to update the release notes?

**Comment by crisner** [comment]
@sagarpreet-chadha, It looks like the commits from the PR #373 is not included in the version when I checked out the zip file here https://github.com/publiclab/leaflet-environmental-layers/releases/tag/2.2.1. It also says so here https://github.com/publiclab/leaflet-environmental-layers/compare/2.2.1...master

Shall we publish these too as it would help to debug some of the errors in plots2? @nstjean, what do you think?

**Comment by crisner** [comment]
@nstjean, could you also take a look at [this](https://github.com/publiclab/leaflet-environmental-layers/releases/tag/2.2.1) and update where needed? Thanks!

**Comment by nstjean** [comment]
@crisner Yes, I will!

**Comment by nstjean** [comment]
@crisner @sagarpreet-chadha I've updated the release notes with the PR that was just merged. This shows the changes you've made and my latest one. So I think we're good!

![FireShot Capture 279 - Comparing 2 2 1 master · publiclab_leaflet-environmental-layers_ - github com](https://user-images.githubusercontent.com/49460529/74347142-a2c10c00-4d7e-11ea-9bcf-c5c76db2ad2e.png)
