### ISSUE TITLE
Weekly community Check-In #48 - Career Options

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-environmental-layers#394]
We all at Public Lab 🎈 - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. We have a Community Check-In each week, where every community member can share something about their work from the past week and about their current week's goal 🎯 . You are also welcome to share fun-fact 😄 , new ideas 💡 , your learning goals ☑️.

We believe in collaborative efforts to support our community. We are running a learning platform which helps a newcomer to become master of tomorrow. 💯

## Think About Your Career :dart: 

This week I'd love everyone to share about what their career plans are! What do you see yourself doing one day? How is your time at Public Lab helping you get there? Or is this your job? What is your next planned step?

## 2020 Software Contributor Community Survey Open :tada: 
Survey ticket is here: #7406
Don't forget our contributor community survey is still open! 

Please give us your thoughts in this anonymous form -- we'll post the results at the end and we can all learn about ourselves! We'll keep it open until March 27, 2020 https://forms.gle/Z6J3Mrdszm9iFiuv9

## GCI Results 
Google has declared the GCI Results for this year at https://codein.withgoogle.com/#winners .
Winners are :
@VladimirMikulic @Uzay-G
Finalists are : 
@HarshKhandeparkar @chen-robert @anthony-zhou @tsparksh

Congratulation!!! :tada: :tada: :confetti_ball: :confetti_ball:

**Comment by nstjean** [comment]
@rehasantiago, @urvashigupta7, @HashTalmiz, @vinitshahdeo, @nstjean, @dragonwarp, @z-arnott, @VladimirMikulic, @NitinBhasneria, @Tlazypanda, @JanviMahajan14, @sssash18, @mantinone, @DouglasLutz, @seabl, @dependabot-preview[bot], @jywarren, @crisner, @Uzay-G, @shaibrown5, @kostogls, @pcube99, @imajit, @nicoleiocana, @simonastefan, @giovannyg, @priyanka-choubey, @anthony-zhou, @hknowlton, @Bhanu-mbvg, @pythongiant

**Comment by nstjean** [comment]
@Rishabh570 @sashadev-skyl @vaibhavmatta @shubhscoder @aSquare14 @sidntrivedi012 @stefannibrasil @ViditChitkara @tech4GT @mridulnagpal @CoderJolly @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab, @ebarry, @jywarren, @sagarpreet-chadha, @JonathanXu1 @rexagod, @divyabaid16, @dinaelhanan, @oorjitchowdhary @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Dhiraj240 @codeIriss @IgorWilbert @pdurbin @HarshKhandeparkar @niravasher @publiclab/reviewers @publiclab/is-reviewers @publiclab/community-reps @divyabaid16 @publiclab/community-reps @subhahu123 @govindjeevan @gautamig54 @rarrunategu1 @CleverFool77 @milaaraujo @kevinzluo @shipcy @developer22-university @keshavsethi @emilyashley @smarty1palak @daemon1024

**Comment by VladimirMikulic** [comment]
@sashadev-sky :)

**Comment by nstjean** [comment]
@alaxalves @keshav234156 @ananyaarun @IshaGupta18 @CodeSarthak @HarshKhandeparkar @chen-robert @LeoDog896 @anthony-zhou

**Comment by nstjean** [comment]
@pydevsg @debck

**Comment by crisner** [comment]
Awesome! I was writing a blog post about career plans after Outreachy! I will share it here as soon as I hit publish. 😄

**Comment by sagarpreet-chadha** [comment]
Awesome! 
My career plan is to work in a team which is excited to explore new things while solving complex interesting problems!!!

**Comment by crisner** [comment]
Here's my blog post, Outreachy week 9 assignment, on career goals, https://renishachristieblog.wordpress.com/2020/02/10/career-goals-after-outreachy/ 😄

**Comment by SidharthBansal** [comment]
**ANNOUNCEMENTS OF THE GCI**
![image](https://user-images.githubusercontent.com/20972099/74193331-33172800-4c7d-11ea-9ca3-615cd677bccc.png)

Well done all the winners :-) Congratulations 🎉 💯 
For the winners, keep up the spirit. This is just the beginning, you have to do much beyond the GCI. World is big and full of opportunities. 💯 
For those you are not winners, even if you created one successful PR that means you learned a lot. That learning is your achievement. You learned Git -> one of the toughest VCS, Software engineering principles, Web Technology and much more. 👍 

Reference: https://codein.withgoogle.com/#winners

Thanks all.

**Comment by nstjean** [comment]
Honestly you all from CGI did so much work, and such good stuff! I've been very impressed. And yes, there is so much learning going on! :fireworks: Fantastic!! :tada: :tada:

**Comment by SidharthBansal** [comment]
Hi Renisha, I really loved your blog post
Can you please repost it to publiclab.org with `soc` tag?
thanks for making this community awesome :-)

**Comment by VladimirMikulic** [comment]
Thank you @SidharthBansal.
Congratulations to you as well, all other mentors, students and volunteers here at Public Lab that have been with us for almost 2 months!
It's been a pleasure to work with this amazing community.

> World is big and full of opportunities. :100: 

I couldn't agree more. Hard work pays off and as you said, this is just the beginning :)

**Comment by crisner** [comment]
Thanks, @SidharthBansal! I'll repost it to publiclab.org.

Congratulations to all GCI winners! 🎉 🎉 🎉

**Comment by cesswairimu** [comment]
My career plan is to work in positive and friendly environment similar to what we have here PL.  PL reminds me that is possible :smiley:  and also I get to contribute and learn from others.

**Comment by cesswairimu** [comment]
Anyone interested in opening this week's check-in?

**Comment by cesswairimu** [comment]
Moved to https://github.com/publiclab/spectral-workbench/issues/482. Thanks everyone
