### ISSUE TITLE
Change sample HTML file to a better layout .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#4]
The HTML file currently shows a map only . We need to add more features to it . 

- [x]  Options to choose layers  ?
<img width="1024" alt="screen shot 2018-05-22 at 5 03 04 pm" src="https://user-images.githubusercontent.com/14952645/40359944-0813e462-5de2-11e8-8397-4ab5b6497ec0.png">

**Comment by jywarren** [comment]
Agreed! Did you add them to a layers control on plots2? Could we do that
here too?

Great work!!!

**Comment by jywarren** [comment]
I guess we should show a layer control in the example but not hard code
that into the library. Just show how it's done, you know?

**Comment by sagarpreet-chadha** [comment]
Done !
Working on second module now :)
<img width="825" alt="screen shot 2018-05-24 at 1 06 23 pm" src="https://user-images.githubusercontent.com/14952645/40471245-aa3795fa-5f53-11e8-93e2-194fc948d5f6.png">

**Comment by sagarpreet-chadha** [comment]
Completed in f430d7ae2709bb14454276294230b8ef92c4e3f1 .

**Comment by jywarren** [comment]
did you find a moment to change it to index.html? Thanks!

**Comment by sagarpreet-chadha** [comment]
Sorry ! I missed that ...done now 👍
