### ISSUE TITLE
Improve layer menu's filtering and layer displaying features

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#408]
The current behaviour of removing a layer(when the layer is turned on) from the menu and the map, when the map view moves out of the layer's extents seems unintuitive as the user might be confused why the layer was missing. @nstjean and I had discussed this in https://github.com/publiclab/leaflet-environmental-layers/issues/399

Below is the solution that would make sense to the user:

> 1) Once a layer is added to the map let the layer be visible both on the map and the layer menu but keep the layer from requesting data if the map is not intersecting with the layer's extents.

Quoting myself as discussed in https://github.com/publiclab/leaflet-environmental-layers/issues/399#issuecomment-584999376

**Comment by neelesh17** [comment]
can I claim this issue?

**Comment by crisner** [comment]
@neelesh17, I am currently working on this issue. 🙂 Would you like to try issue #290 ?

**Comment by neelesh17** [comment]
Yeah sure.
