### ISSUE TITLE
Overload with PurpleAir layer when viewing whole world?

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#41]
I wonder if this is just a too-much-data thing, but pressing the PurpleAir layer at MapKnitter.org seems to stall out the browser -- @sagarpreet-chadha any thoughts?

**Comment by sagarpreet-chadha** [comment]
Yes the only reason is because of conversion of so many data points to Leaflet-markers . 
Although the map becomes little bit laggy with no affect on performance of website on my macbook , but i can understand the scenario in less powerful laptops .

I guess we can for now switch-off the listeners for map panning/zooming and  fetch the data (lots of data!) ONCE . 

What do you think ?

**Comment by jywarren** [comment]
Or what about potentially only displaying this when you zoom in past a
certain level?

**Comment by jywarren** [comment]
This idea of only loading when you zoom in far enough is good for a number of bugs, i think!

**Comment by sagarpreet-chadha** [comment]
Got reply from PurpleAir team : 


The simplest way to download the data is using the download page available at https://www.purpleair.com/sensorlist. This page provides an easy to use interface to download data based on a date range.

- Find and mark the sensor/s in the list you want to download - use CTRL + F to quickly search by sensor name. 
- Return to the top of the page and enter the desired date range, then click Download Selected.

Here is a document to describe how to get the data and what it means:
https://docs.google.com/document/d/15ijz94dXJ-YAZLi9iZ_RaBwrZ4KtYeCy08goGBwnbCU/edit?usp=sharing

PM(#) is the particulate matter size.  
ATM - Atmospheric 
CF_1 - Correction factor of 1 (this is what we use on the map)
UM (uM) - Micrometers and indicates particle counts

ug/m3 - microgram per meter cubed
um/dl - micrometer per deciliter (1/10 of a liter of air)

**Comment by jywarren** [comment]
Hmm, this seems like it'd be for a "Click to download data" link in a
pop-up, but we're hoping to display only data within a bounding box, and
just only trigger a request when the user is zoomed in far enough that the
bounding box isn't too gigantic (like, the whole world at once).

Or, if they have a way to limit the returned results so it doesn't
overwhelm their servers, we could show a subset when you're zoomed out, but
more results for a region when you zoom in. Make sense?

Thanks!

**Comment by sagarpreet-chadha** [comment]
Great ! Got this API link : https://www.purpleair.com/data.json?fetch=true&nwlat=74.54157336289654&selat=-53.01874782140474&nwlng=-265.5250000000093&selng=240.72500000005903

So now we can give bounding rectangle coordinates and also set some zoom level --- above which only we will fetch data .

Thanks 😄 !

**Comment by jywarren** [comment]
ah awesome. great work!
