### ISSUE TITLE
Show a "didn't load" broken icon next to a layer if it fails to fetch data

### ISSUE THREAD

**Issue by crisner** [publiclab/leaflet-environmental-layers#410]
Sometimes layers fail to fetch data from its API. In such cases show a broken icon next to the layer in the layer menu to visually indicate that the data fetch was not successful.

> We could separately decide to show a "didn't load" broken icon like https://fontawesome.com/v4.7.0/icon/exclamation-triangle next to the layer name!

Quoting @jywarren from https://github.com/publiclab/leaflet-environmental-layers/issues/290#issue-532072282

**Comment by neelesh17** [comment]
@crisner is this issue still avalible for claiming.

**Comment by crisner** [comment]
I am working on this today @neelesh17. Would you like to help add a new layer like this issue #122 or help write tests for layers? If you would like to help write tests I can create an issue for you and you could follow the tests that have already been written. Let me know what you are interested to help with. Thanks!

**Comment by neelesh17** [comment]
I would like to help you with issue #122.

**Comment by crisner** [comment]
Excellent! Shall I mention on the issue that you've claimed it?

**Comment by neelesh17** [comment]
Yeah, that would be great.
