### ISSUE TITLE
Browser Menu not displaying correct size and style

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-environmental-layers#420]
I realized what the problem is with the @media queries not working correctly in plots2: it's only checking the size of the *screen*, not the size of the map. If the map is only in the sidebar and is 200px wide the screen is still full size, so it's rendering based on that.

![FireShot Capture 320 - 🎈 Public Lab_ Software Outreach - localhost](https://user-images.githubusercontent.com/49460529/75281761-d455c080-57dd-11ea-8859-1081b50f1d26.png)

Same map, when screen itself is small, working correctly: 
![FireShot Capture 319 - 🎈 Public Lab_ Software Outreach - localhost](https://user-images.githubusercontent.com/49460529/75281773-da4ba180-57dd-11ea-87d6-3f53b2114b35.png)

I'm going to work on this from the plots2 end, but I think we need to have some additional styles for smaller sizes that we can apply and remove as needed. Then we can use javascript to check the width of the map itself.

**Comment by nstjean** [comment]
@crisner

**Comment by crisner** [comment]
Sure. I've have added media queries for all the common breakpoints but the breakpoints may be different as we have to calculate the screen width in plots2. I wonder if we can point to the media query to use based on the screenwidth in JavaScript. I'll look into them. Meanwhile, let me know what sizes you need, I'll work on them.

**Comment by nstjean** [comment]
That would be ideal if we could use the existing media queries! Although I think part of the problem is that widths are specified as percentage of vw, which is not the same as percentage of the map.

The sidebar maps are either 190px or 230px wide at full screen sizes. At tablet sizes the sidebar gets pushed below the screen and the width changes to 670px, then 490px, then smaller and smaller.

The inline maps that are not full-width are typically 800px, but with smaller screen sizes they drop to 690px and then get smaller and smaller.

**Comment by nstjean** [comment]
I tried changing the width from vw to % but it didn't work correctly... I believe because the parent element `.leaflet-control-layers` which is only 48px. We want it to act on the size of the parent .leaflet-map object, and not only once, it should recalculate every time the screen size is changed.

**Comment by crisner** [comment]
Looks like media queries will only take into account the browser window's size. What we want here is what is called as 'container queries'. Take a look at this interesting read. https://philipwalton.com/articles/responsive-components-a-solution-to-the-container-queries-problem/

**Comment by crisner** [comment]
> We want it to act on the size of the parent .leaflet-map object, and not only once, it should recalculate every time the screen size is changed.

This looks useful for our purpose --> https://codeburst.io/media-queries-based-on-element-width-with-mutationobserver-cf2eff172787. What do you think?

**Comment by nstjean** [comment]
Yes! That looks like exactly what we need. It's nice we don't have to build something from scratch!

**Comment by crisner** [comment]
Looks like someone has made a library that would help with this. http://marcj.github.io/css-element-queries/

**Comment by nstjean** [comment]
@crisner I tried that library but I just couldn't get it to work. :( I was bummed.

**Comment by crisner** [comment]
:( But you seem to have figured it out! 🎉
