### ISSUE TITLE
Format marker popups for PLpeople

### ISSUE THREAD

**Issue by nstjean** [publiclab/leaflet-environmental-layers#421]
In LBLD I added a new functionality to have custom code for marker popups: https://github.com/publiclab/leaflet-blurred-location-display/pull/96

Here in LEL I want to use that functionality to customize the marker popups for PLpeople, to look more in line with the content popups in plots2.

**Comment by nstjean** [comment]
![FireShot Capture 322 - Leaflet Environmental Layers - ](https://user-images.githubusercontent.com/49460529/75359986-26045680-5883-11ea-940a-4e97f0e9901c.png)


Does anyone have any input on what should be included in there?

Right now the API includes the following:
```
doc_id: model.id,
doc_type: 'PLACES',
doc_url: model.path,
doc_title: model.username,
latitude: model.lat,
longitude: model.lon,
blurred: model.blurred?,
```

I will be adding a date object so we can calculate how long they have been a member:
```
created_at: model.created_at,
```
and possibly also a profile picture, it would be kind of neat to include a small profile photo. Maybe similar to /people ?
![FireShot Capture 323 - 🎈 Public Lab_ List - publiclab org](https://user-images.githubusercontent.com/49460529/75360145-68c62e80-5883-11ea-9f78-6cf4a7550585.png)

**Comment by jywarren** [comment]
This sounds really great, and this seems like an excellent first draft API to move forward on. Great work!
