### ISSUE TITLE
Links in some layer bubbles not clickable

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#45]
Actually @sagarpreet-chadha  could you update the gh-pages branch so we can test things there too? But I found this was the case for some -- i think SkyTruth but maybe other layers too?

Thanks!!!

**Comment by sagarpreet-chadha** [comment]
Hi !
Updated the branch `gh-pages` . Kindly have a look : 
https://publiclab.github.io/leaflet-environmental-layers/example/index.html#3/43.00/-46.23

**Comment by jywarren** [comment]
Thanks! Yes, it doesn't seem clickable -- so maybe we should make the title into a clickable link, rather than print the link below it: 

![image](https://user-images.githubusercontent.com/24359/43719754-8f97580a-995c-11e8-8a24-3d20b5f96113.png)

What do you think?

**Comment by sagarpreet-chadha** [comment]
Makes sense . Doing the change now .
