### ISSUE TITLE
Basic test failures

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#450]
Hi, i noticed some tests failing on the most recent build -- https://travis-ci.com/github/publiclab/leaflet-environmental-layers/builds/157234331

```
 Basic LEL Implementation
   - leaflet is created...✓ leaflet is created
   - baselayer is added by default...X baselayer is added by default
     TypeError: undefined is not a constructor (evaluating 'new L.Control.GPlaceAutocomplete') in file:///home/travis/build/publiclab/leaflet-environmental-layers/dist/LeafletEnvironmentalLayers_babel.js (line 5139) (1)
```

and more like this. Looks like maybe some assets aren't getting included? But, not sure if this is intermittent or happens every time. I'm restarting the tests to see.

**Comment by crisner** [comment]
@jywarren, it looks like Jasmine is not recognizing the search control. I tried adding it to grunt as a vendor under Jasmine's options and also in the browserify dist src file list but it did not work. Commenting out the search control seems to make the tests pass. I'll try to look into what else can be done for Jasmine to recognize the control as a constructor.

**Comment by jywarren** [comment]
Oh hmm. Do you think it's not recognizing it or perhaps the search controller is not rendering from inside Travis because of approved-domain-name issues? I noticed the search control doesn't start up properly in https://stable.publiclab.org/map as we haven't approved stable.publiclab.org on the Google API end. Could this be the same issue?

**Comment by jywarren** [comment]
I believe this was resolved in the switch to GitHub Actions: https://github.com/publiclab/leaflet-environmental-layers/pull/503
