### ISSUE TITLE
Landfill, mine/quarry map data via OpenStreetMap

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#50]
I found that there is a `landuse=landfill` tag, from https://wiki.openstreetmap.org/wiki/Map_Features

Using that, I made a query on this page: http://harrywood.co.uk/maps/uixapi/xapi.html

http://www.overpass-api.de/api/xapi?*[landuse=landfill][bbox=-118.66693,34.41951,-118.57801,34.46906]

Note this can only be used for very zoomed-in areas, so not for a view of a whole continent or country. 

It shows this output in XML: https://gist.github.com/jywarren/5c0251c0ea3e4c38933bbf0a0d12fc7f

Including:

```
    <tag k="name" v="Chiquita Canyon Landfill"/>
    <tag k="operator" v="Waste Connections Inc"/>
```

Looking for how this could be gotten in JSON; docs here: http://www.overpass-api.de/output_formats.html#json

And it works! See:

https://www.overpass-api.de/api/interpreter?data=[out:json];way[landuse=landfill](34.41951,-118.66693,34.46906,-118.57801);out%20meta;

It's a polygon, the outline of the landfill.

@sagarpreet-chadha, could we use this as an additional layer?

**Comment by sagarpreet-chadha** [comment]
Solved in #94 !
