### ISSUE TITLE
API for indigenous lands

### ISSUE THREAD

**Issue by ebarry** [publiclab/leaflet-environmental-layers#51]
Covering Canada primarily, and most of the rest of North America. Some of Central and South America

https://native-land.ca/api-docs/

**Comment by jywarren** [comment]
@sagarpreet-chadha did you want to link to a single PR where you added a new layer, so it can be an example for newcomers to add layers?

**Comment by sagarpreet-chadha** [comment]
Yes done and added comments in the merged PR as well 😄  .
Opened new  issue here https://github.com/publiclab/leaflet-environmental-layers/issues/55 .

**Comment by jywarren** [comment]
Amazing!

**Comment by ebarry** [comment]
Woohoo!!!!!
