### ISSUE TITLE
Make new layer using API for indigenous lands .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#55]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

We have many layers implemented on this library , see this demo here : 
https://publiclab.github.io/leaflet-environmental-layers/example/index.html#3/43.00/-46.23

Lets add a new layer using this API : 
https://native-land.ca/api-docs/

We can take help from this merged PR [Comments have been added in this PR where changes are required] : 
https://github.com/publiclab/leaflet-environmental-layers/pull/8/files

Happy to help :)

**Comment by SidharthBansal** [comment]
This task is published on GCI dashboard. Thanks all.

**Comment by jywarren** [comment]
:-) go to sleep!

**Comment by kevinzluo** [comment]
@jywarren @SidharthBansal 
Hello

I am currently working on this task for GCI and have encountered a difficulty.
Whenever I try to get the data from the link I encounter a Cross Origin Resource Sharing Blocked message in the console. Could you advise me on how to circumvent this? Only the native-land link is giving this error, while the other layers that have already been implemented pass right through. 

Thank you,
Kevin Luo

**Comment by sagarpreet-chadha** [comment]
@jywarren - do you some people from Native Land ?

I verified and we are getting CORS blocked error 👍 . 
I have messaged them on their website and also on facebook . Lets wait for their reply . 

@kevinzluo --- can you open a Pull Request of the code you have done till now ?
Thanks 😄 🎈  !

**Comment by kevinzluo** [comment]
@jywarren @sagarpreet-chadha 
Hello. I have implemented a Languages Layer now in PR #76 . I am still unable to fetch data using the API. There are also territories and treaties data that I can make 2 other layers for. Would you like me to continue them on the same PR or to make 2 new ones? Thank you.
