### ISSUE TITLE
Add new layer :  Landfill, mine/quarry map data via OpenStreetMap

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#56]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

We have many layers implemented on this library , see this demo here : 
https://publiclab.github.io/leaflet-environmental-layers/example/index.html#3/43.00/-46.23

Lets add a new layer using this API : 
[[See this issue for more details about API]](https://github.com/publiclab/leaflet-environmental-layers/issues/50)

We can take help from this merged PR _[Comments have been added in this PR where changes are required]_ : 
https://github.com/publiclab/leaflet-environmental-layers/pull/8/files

**Happy to help :)**

**Comment by jywarren** [comment]
This was added to the GCI dashboard!

**Comment by kevinzluo** [comment]
Hello. I have claimed this task on the GCI dashboard. I checked out the JSON output and it appears it doesn't give the lat and lng coordinates for each node id. Though we can get this by making more requests, I feel like it would be better to parse the xml instead. I will try working on this.

Thank you,
Kevin Luo
