### ISSUE TITLE
(Mock-up) Make a drawing showing ways to toggle layers

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#60]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Prequistes for solving this issue : 

_Only use of imagination and creativity required !_

### Issue : 

This library uses a button to change layers : 
<img width="860" alt="screenshot 2018-10-12 at 12 01 38 pm" src="https://user-images.githubusercontent.com/14952645/46851896-bb31b700-ce16-11e8-9884-41e08c4274b1.png">

Lets try to figure out a **new , interesting and easy-to-use** way to toggle layers !

### Solution : 

This issue requires you to submit a **drawing** of the solution . 

See this pages for examples : 
https://publiclab.org/questions/warren/04-30-2018/what-are-your-thoughts-on-this-initial-sketch-for-a-tag-page-on-publiclab-org

See these pages for example of maps where we use this button : 
https://publiclab.org/people/
https://publiclab.org/maps/

**Comment by sagarpreet-chadha** [comment]
Possible ideas (open to other solutions as well 😄 ): 

- side menu ?
- scrollable bar (with slideshow type of buttons) ?

**Comment by jywarren** [comment]
Love this!!!!!

**Comment by jywarren** [comment]
Should we mark related ones, so for example the DRAWING ones should link back to the WIREFRAME ones to be completed first?

**Comment by jywarren** [comment]
This was added to the GCI dashboard!

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/52245316-22381780-28af-11e9-9829-63ca2c8ad29c.png)

I did some brainstorming and came up with this!

**Comment by jywarren** [comment]
Maybe like this or something: 
![image](https://user-images.githubusercontent.com/24359/52245442-98d51500-28af-11e9-8b78-4d4a22177be0.png)

**Comment by jywarren** [comment]
This might mean we really need to store the bounding boxes of each layer, so that we can display only ones which have data for the current view.

**Comment by jywarren** [comment]
Also linking this to the MapKnitter design process here: https://github.com/publiclab/mapknitter/issues/327

**Comment by jywarren** [comment]
Also noting @jonathanxu1's work in #61 --

![info](https://user-images.githubusercontent.com/22998430/49334831-a7e8cf80-f5ad-11e8-89f7-21b5d33d6dd4.png)

**Comment by jywarren** [comment]
I think we could use some of @jonathanxu1's design ideas in the table view as well. I especially like the icons. We could use some from the Noun Project, maybe.

**Comment by jywarren** [comment]
Closing in favor of new menu ideas in #232
