### ISSUE TITLE
(Mock-up) Make a wireframe showing easy way for toggling layers . 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#61]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Prequistes for solving this issue : 

We can use any of these to solve this issue :

1.) wireframe tools (like https://moqups.com/ )
2.) Photoshop
3.) Paint 
4.) Any other wireframe tool .

_AND Use of imagination and creativity also required !_
 
### Issue : 

This library uses a button to change layers : 
<img width="860" alt="screenshot 2018-10-12 at 12 01 38 pm" src="https://user-images.githubusercontent.com/14952645/46851896-bb31b700-ce16-11e8-9884-41e08c4274b1.png">

Lets try to figure out a **new , interesting and easy-to-use** way to toggle layers !

### Solution : 

This issue requires you to submit a **WIREFRAME** of the solution . 

See this pages for examples : 
https://publiclab.org/questions/warren/04-30-2018/what-are-your-thoughts-on-this-initial-sketch-for-a-tag-page-on-publiclab-org
https://publiclab.org/wiki/ui

See these pages for example of maps where we use this button : 
https://publiclab.org/people/
https://publiclab.org/maps/

**Comment by sagarpreet-chadha** [comment]
Possible ideas (open to other solutions as well 😄 ): 

- side menu ?
- scrollable bar (with slideshow type of buttons) ?

**Comment by jywarren** [comment]
This was added to the GCI dashboard!

**Comment by JonathanXu1** [comment]
Hey there, I've made a wireframe using photoshop.

There'll be an options button in the bottom left:
![layer-off](https://user-images.githubusercontent.com/22998430/49330722-7c8bc380-f560-11e8-99bd-03558ae40384.png)

When selected, a list of options can be toggled like shown:
![layer-on](https://user-images.githubusercontent.com/22998430/49330721-7b5a9680-f560-11e8-9634-506ecce0184e.png)

My design has been inspired by this: https://carto.com/help/images/working-with-data/carto-editor/maps/map_display_options.jpg

**Comment by JonathanXu1** [comment]
Cool! Let me know if there's anything else you need, or if this task can be posted and claimed on the dashboard. Thanks

**Comment by jywarren** [comment]
This is great! I wonder if you could consider adding some kind of link to
more information about each layer. Maybe it could be an icon or a column in
the key you've drawn?

**Comment by JonathanXu1** [comment]
![info](https://user-images.githubusercontent.com/22998430/49334831-a7e8cf80-f5ad-11e8-89f7-21b5d33d6dd4.png)
How's this?

**Comment by JonathanXu1** [comment]
@jywarren @sagarpreet-chadha

**Comment by sagarpreet-chadha** [comment]
Hi @JonathanXu1 ,
This is really fantastic 🎉 ! 
Also have you claimed this issue on GCI dashboard ? I couldn't find this task instance claimed . 
Thanks 😄 !

**Comment by JonathanXu1** [comment]
Hi @sagarpreet-chadha , I couldn't find the task on GCI and asked if it was created as an instance in codein above. Perhaps it's marked as a beginner task though this issue is tagged only as gci-candidate?

**Comment by jywarren** [comment]
Love it!

**Comment by JonathanXu1** [comment]
This could also solve #65 . However I can't find the link to the task. Is it posted?

**Comment by JonathanXu1** [comment]
Just checking back on whether this can be made available on gci.

**Comment by JonathanXu1** [comment]
@sagarpreet-chadha ? Sorry to bother you.

**Comment by sagarpreet-chadha** [comment]
Hi apologies for late response . I am making a GCI task right now , it will be soon published .

**Comment by sagarpreet-chadha** [comment]
Oh i see it is already added 😄 !

https://codein.withgoogle.com/dashboard/tasks/4668534585032704/

I will approve the task as soon as you claim it ! Thank you :)

**Comment by JonathanXu1** [comment]
Sorry it turns out this is a beginner task! There was no mention of this being beginner or fto which was why claimed it. Sorry about the misunderstanding

**Comment by JonathanXu1** [comment]
Sorry it turns out this is a beginner task! There was no mention of this being beginner or fto which was why worked on it. Sorry about the misunderstanding

**Comment by jywarren** [comment]
I'm going to consolidate a bit and merge this into #60 ! Thanks, all!
