### ISSUE TITLE
(Mock-up) Make Drawings showing way to tell people about Layers button .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#62]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Prequistes for solving this issue : 

_Only use of imagination and creativity required !_

### Issue : 

This library uses a button to change layers : 
<img width="860" alt="screenshot 2018-10-12 at 12 01 38 pm" src="https://user-images.githubusercontent.com/14952645/46851896-bb31b700-ce16-11e8-9884-41e08c4274b1.png">

The users do not use this layers button as they do not know that such a button exists !
We need to figure out a way to tell users about this layer-button such that it : 
1.) does not distract the user while using the map .
2.) easily tells the user about this button .
3.) matches with the color code of publiclab.org website .

### Solution : 

This issue requires you to submit a **drawing** of the solution . 

See this pages for examples : 
https://publiclab.org/questions/warren/04-30-2018/what-are-your-thoughts-on-this-initial-sketch-for-a-tag-page-on-publiclab-org

See these pages for example of maps where we use this button : 
https://publiclab.org/people/
https://publiclab.org/maps/

**Comment by sagarpreet-chadha** [comment]
Possible solutions (open to new solutions as well) : 
-  pop-up screen  ?
- something on map ?
- text written below each map on publiclab.org . 
- some animation ?

**Comment by jywarren** [comment]
This was added to the GCI dashboard!

**Comment by jywarren** [comment]
:-) got excited and tried out an idea:

![image](https://user-images.githubusercontent.com/24359/49522484-c385fb80-f875-11e8-8870-2783cb2e3846.png)

In this mockup document anyone can edit! https://docs.google.com/presentation/d/1TCZoTfuhamRVrUak8aDgqJAwSgyhRtZg2Pgacl2_4zc/edit#slide=id.g4877128470_0_0

**Comment by sagarpreet-chadha** [comment]
Awesome.....I will try to code this 💛 !
