### ISSUE TITLE
(Mock-up) Make WIREFRAME showing way to tell people about Layers button .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#63]
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

### Prequistes for solving this issue : 

We can use any of these to solve this issue :

1.) wireframe tools (like https://moqups.com/ )
2.) Photoshop
3.) Paint 
4.) Any other wireframe tool .

_AND Use of imagination and creativity also required !_
 
### Issue : 

This library uses a button to change layers : 
<img width="860" alt="screenshot 2018-10-12 at 12 01 38 pm" src="https://user-images.githubusercontent.com/14952645/46851896-bb31b700-ce16-11e8-9884-41e08c4274b1.png">

The users do not use this layers button as they do not know that such a button exists !
We need to figure out a way to tell users about this layer-button such that it : 
1.) does not distract the user while using the map .
2.) easily tells the user about this button .
3.) matches with the color code of publiclab.org website .

### Solution : 

This issue requires you to submit a **WIREFRAME** of the solution . 

See this pages for examples : 
https://publiclab.org/questions/warren/04-30-2018/what-are-your-thoughts-on-this-initial-sketch-for-a-tag-page-on-publiclab-org
https://publiclab.org/wiki/ui

See these pages for example of maps where we use this button : 
https://publiclab.org/people/
https://publiclab.org/maps/

**Comment by sagarpreet-chadha** [comment]
Possible solutions (open to new solutions as well) : 
-  pop-up screen  ?
- something on map ?
- text written below each map on publiclab.org . 
- some animation ?

**Comment by jywarren** [comment]
This was added to the GCI dashboard!

**Comment by jywarren** [comment]
Merging this into #62!
