### ISSUE TITLE
odor reports Layer

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#7]
odor reports via https://odorlog.ushahidi.io/ via Ushahidi API

API : https://odorlog.api.ushahidi.io/api/v3/posts/

* [x] create a new layer that can be enabled/disabled with http://leafletjs.com/examples/layers-control/
* [x] add a custom icon with http://leafletjs.com/examples/custom-icons/

Marker Url : https://www.clker.com/cliparts/T/3/6/T/S/8/ink-splash-md.png

**Comment by jywarren** [comment]
Awesome! :-)

**Comment by sagarpreet-chadha** [comment]
@jywarren  Added this layer also ! Kindly have a look :)
<img width="376" alt="screen shot 2018-06-03 at 2 09 08 am" src="https://user-images.githubusercontent.com/14952645/40880743-ff839806-66d3-11e8-91bd-b3ae14f9a42e.png">

**Comment by jywarren** [comment]
Oh wow. Shall we merge this and see what the odor logging people say? They'll have suggestions I bet.

**Comment by sagarpreet-chadha** [comment]
Thanks :)
I have pushed the code to master and gh-pages branch . Should i make a PR first before merging to master branch from now on ?

**Comment by jywarren** [comment]
Yes, that's good practice to leave a trail others can follow. I sometimes
push directly when I'm just starting a project, but as soon as I'm starting
to think about building a community out, I'll start making PRs to build
conventions -- as an example. Thanks for asking!

**Comment by jywarren** [comment]
Do you want to make a research note on publiclab.org and mention @xose to
share what you did?

**Comment by jywarren** [comment]
You could embed the demo map into the note!

**Comment by sagarpreet-chadha** [comment]
xose  mentioned some points here  : 
https://publiclab.org/notes/sagarpreet/06-06-2018/leaflet-environmental-layer-library#c19806

**Comment by sagarpreet-chadha** [comment]
Completed in b5fd8fdbf388e059686ec5e962d89f382a4d85e6 .
