### ISSUE TITLE
Show small spinner while new layers are loading

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#72]
... in upper left corner of map?

This is just a UI idea because some layers are slow, so it could be useful. Alternatively we could show a spinner next to their checkboxes, and that might be easier!

**Comment by sagarpreet-chadha** [comment]
Working on this !

**Comment by sagarpreet-chadha** [comment]
GIF : 

**Spinner at the center** 😄 !

![spinner_gif](https://user-images.githubusercontent.com/14952645/48554168-a8257180-e903-11e8-8e90-074774206830.gif)
