### ISSUE TITLE
Make FracTracker layer live-loading by parsing CSV

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#73]
The FracTracker layer is currently static, because we need to parse a CSV into JSON. I think we can do that in code, dynamically. 

The source is here: https://github.com/publiclab/leaflet-environmental-layers/blob/master/src/fractracker.js

This map shows the location of organizations working on oil & gas issues in the US and internationally.
http://ft.maps.arcgis.com/apps/Embed/index.html?appid=8defce10bdc64a35ae4fd3997edd2b1e

The data set of this map is here :
https://docs.google.com/spreadsheets/d/19j4AQmjWuELuzn1GIn0TFRcK42HjdHF_fsIa8jtM1yw/pub?gid=288258812&single=true&output=csv

Here is a range of CSV to JSON parsers we might use! https://www.npmjs.com/search?q=parse%20csv

Eventually we might make CSV and XML parsing a utility of the whole library, since we might anticipate having to do this kind of parsing with lots of APIs.

Here's some interesting code that is parsing XML into JSON, for reference:

http://darinacosta.com/skytruth/src/dataManager.js (http://darinacosta.com/skytruth/ live)

**Comment by jywarren** [comment]
(accidentally mentioned @sagarpreet-chadha as I was typing this, so this may be interesting to you but I didn't mean to make a request yet! 😄 )

**Comment by kevinzluo** [comment]
@jywarren @sagarpreet-chadha 
I don't believe I see this one added to the GCI dashboard. Could it be added? I would like to work on it.

**Comment by kevinzluo** [comment]
@sagarpreet-chadha 
Would you mind taking a look at this?

**Comment by sagarpreet-chadha** [comment]
Okay , let me check 👍

**Comment by sagarpreet-chadha** [comment]
Hi @kevinzluo ,
I have made the task on GCI dashboard for this issue and will be soon published . You may start working on this issue . 

@SidharthBansal , @jywarren ...kindly publish this new task on GCI dashboard 😄 !

**Comment by kevinzluo** [comment]
Thank you!

**Comment by SidharthBansal** [comment]
Please claim it if you have not claimed it still.

**Comment by SidharthBansal** [comment]
https://codein.withgoogle.com/dashboard/tasks/5421884796567552/
Published on the GCI dashboard
Thanks for reporting
