### ISSUE TITLE
Add FracTracker mobile app data layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#87]
FracTracker mobile app reports seem to be loaded via requests like this:

https://services.arcgis.com/jDGuO8tYggdCCnUJ/arcgis/rest/services/FracTrackerMobileAppNPCAMesaVerdeNationalPark_051416/FeatureServer/0/query?f=pbf&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=8000&resultType=tile&quantizationParameters=%7B%22mode%22%3A%22edit%22%7D

Looks like arcgis FeatureLayer -- there's a plugin for them! https://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html

These are loaded under the Photo Documentation layer (2nd to last) here: http://ft.maps.arcgis.com/apps/MapJournal/index.html?appid=acb8b266e60446a2bf3fac099827c163

And are reported via the FracTracker app: https://play.google.com/store/apps/details?id=com.viableindustries.fractracker&hl=en

Response seems to be in "pbf" format... but changing `pbf` to `json` works:

https://services.arcgis.com/jDGuO8tYggdCCnUJ/arcgis/rest/services/FracTrackerMobileAppNPCAMesaVerdeNationalPark_051416/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=102100&resultOffset=0&resultRecordCount=8000&resultType=tile&quantizationParameters=%7B%22mode%22%3A%22edit%22%7D

I think this should be pretty easy to add! @sagarpreet-chadha what do you think?

**Comment by sagarpreet-chadha** [comment]
Awesome !!!

**Comment by jywarren** [comment]
Ah, it looks like we need to use a broader URL -- this is only the Mesa Verde region. I'm asking for a broader link to all mobile app reports!

**Comment by jywarren** [comment]
OK, I found that there is now a Leaflet-compatible API endpoint here! 

https://api.fractracker.org/v1/data/report?page=1&q=%7B"filters":%5B%7B"name":"geometry","op":"intersects","val":"SRID%3D4326;POLYGON((-107.50990585750145+43.40852567953252,-88.15199570125245+43.40852567953252,-88.15199570125245+34.907879278458125,-107.50990585750145+34.907879278458125,-107.50990585750145+43.40852567953252))"%7D%5D,"order_by":%5B%7B"field":"report_date","direction":"desc"%7D,%7B"field":"id","direction":"desc"%7D%5D%7D

I think there are 4 bounding box corners in there, and the rest can be left as it is. The returned data may be... GeoJSON? 

```js
{
  "features": [
    {
      "geometry": {
        "geometries": [
          {
            "coordinates": [
              -97.0869865947289, 
              36.6809097940478
            ], 
            "type": "Point"
          }
        ], 
        "type": "GeometryCollection"
      }, 
      "id": 2057, 
      "properties": {
        "created_by": {
          "geometry": null, 
          "id": 940, 
          "properties": {
            "active": true, 
            "bio": null, 
            "confirmed_at": null, 
            "current_login_at": "2019-07-25T15:28:19.331920", 
            "email": "lauriebarr59@yahoo.com", 
            "first_name": "Laurie", 
            "id": 940, 
            "last_login_at": "2019-07-25T15:26:30.916616", 
            "last_name": "Barr", 
            "login_count": 6, 
            "organization_name": "save our streams pa", 
            "picture": "https://api.fractracker.org/static/usercontent/FS_9f76fce712f74bd7b365166c9ffb39b8_thumbnail.jpg", 
            "screen_name": "SOSPA", 
            "title": null
          }, 
          "type": "Feature"
        }, 
```

It even includes images like this: 

![](https://api.fractracker.org/static/usercontent/FS_0c4b27db17474353a3a6c580ce8da0d9_thumbnail.jpg)

Awesome!

**Comment by jywarren** [comment]
Darn! CORS permissions are set on the source. I'll ask if they can remove them. This should otherwise work, i think?

```js
$.get(
  'https://api.fractracker.org/v1/data/report?page=1&q=%7B%22filters%22:%5B%7B%22name%22:%22geometry%22,%22op%22:%22intersects%22,%22val%22:%22SRID%3D4326;POLYGON((-107.50990585750145+43.40852567953252,-88.15199570125245+43.40852567953252,-88.15199570125245+34.907879278458125,-107.50990585750145+34.907879278458125,-107.50990585750145+43.40852567953252))%22%7D%5D,%22order_by%22:%5B%7B%22field%22:%22report_date%22,%22direction%22:%22desc%22%7D,%7B%22field%22:%22id%22,%22direction%22:%22desc%22%7D%5D%7D')
  .done(function(data) {
    L.geoJSON(data, {
      style: function (feature) {
        return {color: 'green'};
      }
    }).bindPopup(function (layer) {
      return layer.feature.properties.organization_name;
    }).addTo(map645); // <= here we need to put the Leaflet map object. 
});
```

**Comment by sagarpreet-chadha** [comment]
Yes should work fine.

**Comment by ananyaarun** [comment]
This issue in LEL is reserved for GCI students.
Thanks !!

**Comment by jywarren** [comment]
Noting that the CORS is still not resolved. But we may be able to use https://corsproxy.github.io/ to get around this restriction for now!

**Comment by jywarren** [comment]
So that'd be: https://crossorigin.me/https://api.fractracker.org/v1/data/report?page=1&q=%7B%22filters%22:%5B%7B%22name%22:%22geometry%22,%22op%22:%22intersects%22,%22val%22:%22SRID%3D4326;POLYGON((-107.50990585750145+43.40852567953252,-88.15199570125245+43.40852567953252,-88.15199570125245+34.907879278458125,-107.50990585750145+34.907879278458125,-107.50990585750145+43.40852567953252))%22%7D%5D,%22order_by%22:%5B%7B%22field%22:%22report_date%22,%22direction%22:%22desc%22%7D,%7B%22field%22:%22id%22,%22direction%22:%22desc%22%7D%5D%7D

I think! But hmm. Looks like that didn't work. Maybe that proxy is no longer running.

**Comment by jywarren** [comment]
Yes, this worked!

```js
$.get(
  'https://cors-anywhere.herokuapp.com/https://api.fractracker.org/v1/data/report?page=1&q=%7B%22filters%22:%5B%7B%22name%22:%22geometry%22,%22op%22:%22intersects%22,%22val%22:%22SRID%3D4326;POLYGON((-107.50990585750145+43.40852567953252,-88.15199570125245+43.40852567953252,-88.15199570125245+34.907879278458125,-107.50990585750145+34.907879278458125,-107.50990585750145+43.40852567953252))%22%7D%5D,%22order_by%22:%5B%7B%22field%22:%22report_date%22,%22direction%22:%22desc%22%7D,%7B%22field%22:%22id%22,%22direction%22:%22desc%22%7D%5D%7D')
  .done(function(data) {
    L.geoJSON(data, {
      style: function (feature) {
        return {color: 'green'};
      }
    }).bindPopup(function (layer) {
      return layer.feature.properties.organization_name;
    }).addTo(map); // <= here we need to put the Leaflet map object. 
});
```

**Comment by jywarren** [comment]
However, we'll want to replace the coordinates in that URL with the current bounding box coordinates, and refresh the remote request each time the view moves. There are a couple examples of how to do this; one is here:

https://gis.stackexchange.com/questions/174721/how-to-add-remote-geojson-data-to-a-leaflet-map-as-a-new-layer

The other is a whole plugin to manage this kind of thing, and it looks pretty straightforward too!

https://github.com/Dominique92/Leaflet.GeoJSON.Ajax

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/69171399-dcf57700-0ac9-11ea-823f-8d67a1414ddb.png)

**Comment by jywarren** [comment]
Just to note for documentation, i ended up using: https://github.com/Rob--W/cors-anywhere/#documentation

**Comment by jywarren** [comment]
And noting, here's a reference for a layer that refreshes as you drag around, with new requests sent each time, using the `moveend` event to trigger a refresh:

https://github.com/publiclab/leaflet-environmental-layers/blob/e58d33ade28df744baadefd4557b991bedbdb9a3/src/indigenousLayers.js#L20-L64

And here's the existing layer we want to update!

https://github.com/publiclab/leaflet-environmental-layers/blob/master/src/fracTrackerMobileLayer.js
