### ISSUE TITLE
Add Luftdaten.info air quality layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#88]
https://luftdaten.info/en/home-en/

https://usa.maps.luftdaten.info/#4/40.00/-100.00

Leaflet based! So should be VERY easy!

**Comment by rkpattnaik780** [comment]
I would like to work on this one.

**Comment by sagarpreet-chadha** [comment]
Hi ! Please go ahead :)

**Comment by rkpattnaik780** [comment]
@sagarpreet-chadha since it is my first time adding a layer, can you send me some resources to help me get started, maybe a PR from the past?

**Comment by gauravano** [comment]
Hey @rkpattnaik780, you can refer to the closed PRs of the project where the layer has been added - https://github.com/publiclab/leaflet-environmental-layers/pulls?q=is%3Apr+is%3Aclosed .

**Comment by rkpattnaik780** [comment]
> Hey @rkpattnaik780, you can refer to the closed PRs of the project where the layer has been added - https://github.com/publiclab/leaflet-environmental-layers/pulls?q=is%3Apr+is%3Aclosed .

Thanks, I am on it :)

**Comment by gauravano** [comment]
Great!
