### ISSUE TITLE
Wisconsin non-metallic mining layer

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#89]
https://www.fractracker.org/2018/11/wisconsin-nonmetallic-mining/

this is also an ESRI layer - see #87 for how to integrate this -- but for a narrow region. Perhaps we could prototype only displaying some layers in the menu if you're in the right region of the world and right zoom level?

**Comment by jywarren** [comment]
Sample API query in ESRI JSON: https://services.arcgis.com/jDGuO8tYggdCCnUJ/arcgis/rest/services/Nonmetallic_and_Potential_frac_sand_mine_proposals_in_West_Central_Wisconsin/FeatureServer/0/query?f=json&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22xmin%22%3A-10043214.020446243%2C%22ymin%22%3A4984917.236647738%2C%22xmax%22%3A-9368122.186631741%2C%22ymax%22%3A5660009.07046224%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&returnCentroid=true&returnExceededLimitFeatures=false&maxRecordCountFactor=3&orderByFields=GISACRES%20DESC&outSR=102100&resultType=tile&quantizationParameters=%7B%22mode%22%3A%22view%22%2C%22originPosition%22%3A%22upperLeft%22%2C%22tolerance%22%3A1222.992452562501%2C%22extent%22%3A%7B%22xmin%22%3A-10018754.171394993%2C%22ymin%22%3A5009377.085698988%2C%22xmax%22%3A-9392582.035682991%2C%22ymax%22%3A5635549.221410989%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%2C%22latestWkid%22%3A3857%7D%7D%7D

But we should compare to this map to ensure we get the right data - there are multiple types:

![image](https://user-images.githubusercontent.com/24359/49171751-38ed4b80-f30d-11e8-9215-12c60d652991.png)

**Comment by ananyaarun** [comment]
Closing as this as been added and merged ! thanks.
