### ISSUE TITLE
Change the colors or add images of marker in layer selection menu .

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/leaflet-environmental-layers#9]
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

We have a demo map here : 
https://publiclab.github.io/leaflet-environmental-layers/example/mapSimple.html

# Problem : 
On the right most corner , you will find a button with options to choose different layers . However if one selects more than a layer at a time then there might be ambiguity that **which marker belongs to which layer .**
<img width="204" alt="screen shot 2018-06-05 at 2 45 48 pm" src="https://user-images.githubusercontent.com/14952645/40966820-29451a6e-68cf-11e8-9089-cdd2ddd2046b.png">

# Solution : 
1.) Lets add color to layer-name in the menu : 
Example : 
https://github.com/publiclab/leaflet-environmental-layers/blob/b5fd8fdbf388e059686ec5e962d89f382a4d85e6/example/mapSimple.html#L69
can be changed to : 
`"<span style='color: red'>SkyTruth</strong>": SkyTruth , `
#### output : 
<img width="173" alt="screen shot 2018-06-05 at 2 41 35 pm" src="https://user-images.githubusercontent.com/14952645/40966921-64ab323c-68cf-11e8-9823-a2c732c6fca9.png">

2.) Or we add the marker itself along with the layer name like this : 
` "<img src='https://www.clker.com/cliparts/T/G/b/7/r/A/red-dot.svg' height='20px' width='30px'>SkyTruth": SkyTruth , `
#### output : 
<img width="199" alt="screen shot 2018-06-05 at 2 41 12 pm" src="https://user-images.githubusercontent.com/14952645/40967118-e588f060-68cf-11e8-9755-c4a97d117b4f.png">

*  **You can use combination of above 2 solutions for all layers .**

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

**Comment by Rishabh570** [comment]
@sagarpreet-chadha I would like to work on this issue
