### ISSUE TITLE
Odd error on inline map on plots2

### ISSUE THREAD

**Issue by jywarren** [publiclab/leaflet-environmental-layers#90]
Hi, @sagarpreet-chadha - not sure what's causing this but maybe the spinner library? https://publiclab.org/wiki/advanced-grids

**Comment by jywarren** [comment]
Do we maybe need to figure out how to run JavaScript tests on plots2 or something as these are seeming to be a bit brittle...

**Comment by sagarpreet-chadha** [comment]
@jywarren ...did you run` npm install` ? We need leaflet-spin library in **lib** folder .

**Comment by jywarren** [comment]
hmm, this is on production... we're using `yarn` now -- do we need to add
leaflet-spin library to our package.json in plots2?

Thanks!

**Comment by sagarpreet-chadha** [comment]
It is already added to package.json .

**Comment by sagarpreet-chadha** [comment]
`<%= javascript_include_tag('/lib/leaflet-spin/example/leaflet.spin.min.js') %>`
This is the path i have given in the code . Just confirming that this is the path where yarn installs the library . Thanks !

**Comment by sagarpreet-chadha** [comment]
Okay...i am quite sure we are not running on latest version of LEL and do not have Leaflet-spinner library on production .

**Comment by jywarren** [comment]
well, i can redeploy to production now if it'll help?

**Comment by sagarpreet-chadha** [comment]
Okay great ! and i guess **yarn upgrade**  also ?

**Comment by jywarren** [comment]
I believe so - well, actually not sure --
https://github.com/publiclab/plots2/search?q=yarn but maybe we should check
with @icarito and @souravirus if yarn upgrade is necessary?

**Comment by jywarren** [comment]
ah ok! So perhaps in one of the files in that search link we ought to add a
`yarn update` after `yarn install`?

**Comment by Souravirus** [comment]
Yeah, these commands would probably work. But to prevent some errors to create the yarn.lock file. Use this command `yarn --ignore-engines --ignore-scripts`.

**Comment by jywarren** [comment]
Sagarpreet would you like to open a PR for this on plots2 to see how it
does? Perhaps push to unstable to check? Thanks!

**Comment by jywarren** [comment]
@Souravirus @sagarpreet-chadha would we add a new command at the end of this one: 

https://github.com/publiclab/plots2/blob/5c2bce348f841a9b37cce473e1279c27e20e794d/.travis.yml#L22

Right now it says 


but Sourav, are you meaning the new addition should say

**Comment by jywarren** [comment]
Are we extra sure that we've bumped the version number and should be getting the latest? Can we test this on unstable as well to test it out?

**Comment by jywarren** [comment]
Thanks everyone for working this issue!

**Comment by icarito** [comment]
Hi,
We run a semi-automated deployment process based in our [Makefile](https://github.com/publiclab/plots2/blob/master/Makefile#L24).
In so far as I recall we have an issue that we "shadow" the js libs when we mount the app volume. That's why we run docker-compose exec -T web yarn install in order to update dependencies on the mounted volume (the host filesystem).
@Souravirus I think we already run `yarn --ignore-engines --ignore-scripts` from [.yarnrc](https://github.com/publiclab/plots2/blob/master/.yarnrc).
@jywarren I think you are likely right that what is required is to add yarn update step (or solve the underlaying volume shadowing of javascript public/libs directory).

**Comment by Souravirus** [comment]
@jywarren to upgrade the lel version in yarn just update the version in package.json and do a `yarn install` command. This would update the yarn.lock file. Now just merge this yarn.lock file and with the current command it would work.

Sorry for the delay in answer. Actually I am busy in our final exams.
